import bcrypt from 'bcryptjs';

export async function getSeedData() {
  const adminPasswordHash = await bcrypt.hash('ExamAdmin@2026', 10);
  const studentPasswordHash = await bcrypt.hash('Student@1234', 10);
  const verifierPasswordHash = await bcrypt.hash('Verifier@2026', 10);

  const states = [
    { code: 'IN-MP', name: 'Madhya Pradesh', type: 'state', capital: 'Bhopal' },
    { code: 'IN-DL', name: 'Delhi', type: 'ut', capital: 'New Delhi' },
    { code: 'IN-UP', name: 'Uttar Pradesh', type: 'state', capital: 'Lucknow' },
    { code: 'IN-MH', name: 'Maharashtra', type: 'state', capital: 'Mumbai' },
    { code: 'IN-RJ', name: 'Rajasthan', type: 'state', capital: 'Jaipur' },
    { code: 'IN-BR', name: 'Bihar', type: 'state', capital: 'Patna' },
    { code: 'IN-KA', name: 'Karnataka', type: 'state', capital: 'Bengaluru' },
    { code: 'IN-TN', name: 'Tamil Nadu', type: 'state', capital: 'Chennai' },
    { code: 'IN-WB', name: 'West Bengal', type: 'state', capital: 'Kolkata' },
    { code: 'IN-GJ', name: 'Gujarat', type: 'state', capital: 'Gandhinagar' },
    { code: 'IN-HR', name: 'Haryana', type: 'state', capital: 'Chandigarh' },
    { code: 'IN-PB', name: 'Punjab', type: 'state', capital: 'Chandigarh' },
    { code: 'IN-TS', name: 'Telangana', type: 'state', capital: 'Hyderabad' },
    { code: 'IN-AP', name: 'Andhra Pradesh', type: 'state', capital: 'Amaravati' },
    { code: 'IN-KL', name: 'Kerala', type: 'state', capital: 'Thiruvananthapuram' },
    { code: 'IN-JK', name: 'Jammu & Kashmir', type: 'ut', capital: 'Srinagar' },
    { code: 'IN-UK', name: 'Uttarakhand', type: 'state', capital: 'Dehradun' },
  ];

  const categories = [
    { name: 'Engineering Entrance', slug: 'engineering-entrance', icon: 'Cpu', description: 'National and state level engineering admissions (JEE, BITSAT, State CETs)' },
    { name: 'Medical Entrance', slug: 'medical-entrance', icon: 'Activity', description: 'Medical, dental, and AYUSH degree admissions (NEET UG, NEET PG)' },
    { name: 'Class 10 & 12 School Boards', slug: 'school-boards', icon: 'GraduationCap', description: 'CBSE, ICSE, NIOS, MPBSE, and State Higher Secondary Board examinations' },
    { name: 'Civil Services & UPSC', slug: 'civil-services', icon: 'Landmark', description: 'Union Public Service Commission and State Public Service Commissions' },
    { name: 'Staff Selection (SSC)', slug: 'staff-selection', icon: 'FileCheck', description: 'CGL, CHSL, MTS, CPO recruitment examinations' },
    { name: 'Banking & Insurance', slug: 'banking-insurance', icon: 'Building2', description: 'IBPS PO/Clerk, SBI PO/Clerk, RBI Grade B examinations' },
    { name: 'Defence & Paramilitary', slug: 'defence-services', icon: 'Shield', description: 'NDA, CDS, AFCAT, CAPF, Indian Coast Guard' },
    { name: 'Railways (RRB)', slug: 'railways-rrb', icon: 'Train', description: 'RRB NTPC, Group D, ALP, Technician recruitment' },
    { name: 'University Entrance', slug: 'university-entrance', icon: 'BookOpen', description: 'CUET UG, CUET PG, central and state university admissions' },
    { name: 'Law Entrance', slug: 'law-entrance', icon: 'Scale', description: 'CLAT UG/PG, AILET, LSAT India' },
    { name: 'Management Entrance', slug: 'management-entrance', icon: 'Briefcase', description: 'CAT, XAT, MAT, CMAT admissions to IIMs and B-Schools' },
    { name: 'Teaching & TET', slug: 'teaching-exams', icon: 'Award', description: 'CTET, State TETs, KVS, NVS teaching eligibility' },
    { name: 'Scholarships & Fellowships', slug: 'scholarships-fellowships', icon: 'Sparkles', description: 'Merit-based and means-based financial aid programs' },
  ];

  const organizations = [
    {
      name: 'National Testing Agency',
      short_name: 'NTA',
      slug: 'nta',
      official_domain: 'nta.ac.in',
      description: 'Autonomous premier testing organization established by Ministry of Education, Govt of India.',
      org_type: 'national_testing',
      official_portal_url: 'https://nta.ac.in',
      helpline_number: '011-40759000',
      contact_email: 'neet@nta.ac.in',
      is_verified: true,
    },
    {
      name: 'Union Public Service Commission',
      short_name: 'UPSC',
      slug: 'upsc',
      official_domain: 'upsc.gov.in',
      description: 'Premier central recruiting agency responsible for appointments to All India services and Central civil services.',
      org_type: 'commission',
      official_portal_url: 'https://upsc.gov.in',
      helpline_number: '011-23385271',
      contact_email: 'feedback-upsc@gov.in',
      is_verified: true,
    },
    {
      name: 'Staff Selection Commission',
      short_name: 'SSC',
      slug: 'ssc',
      official_domain: 'ssc.gov.in',
      description: 'Recruitment organization for non-gazetted group B and C posts in Ministries and Departments of Govt of India.',
      org_type: 'recruitment',
      official_portal_url: 'https://ssc.gov.in',
      helpline_number: '1800-309-3063',
      contact_email: 'enquiry-ssc@nic.in',
      is_verified: true,
    },
    {
      name: 'Central Board of Secondary Education',
      short_name: 'CBSE',
      slug: 'cbse',
      official_domain: 'cbse.gov.in',
      description: 'National board of education in India for public and private schools under the Union Government.',
      org_type: 'board',
      official_portal_url: 'https://cbse.gov.in',
      helpline_number: '1800-11-8002',
      contact_email: 'info.cbse@gov.in',
      is_verified: true,
    },
    {
      name: 'Madhya Pradesh Board of Secondary Education',
      short_name: 'MPBSE',
      slug: 'mpbse',
      official_domain: 'mpbse.nic.in',
      description: 'State government body responsible for determining policy-related, administrative, cognitive, and intellectual direction of MP state education system.',
      org_type: 'board',
      official_portal_url: 'https://mpbse.nic.in',
      helpline_number: '1800-233-0175',
      contact_email: 'mpbse@mp.nic.in',
      is_verified: true,
    },
    {
      name: 'Madhya Pradesh Public Service Commission',
      short_name: 'MPPSC',
      slug: 'mppsc',
      official_domain: 'mppsc.mp.gov.in',
      description: 'State agency authorized to conduct the State Services Examination for civil service posts in Madhya Pradesh.',
      org_type: 'commission',
      official_portal_url: 'https://mppsc.mp.gov.in',
      helpline_number: '0731-2491033',
      contact_email: 'mppsc@mp.gov.in',
      is_verified: true,
    },
    {
      name: 'Institute of Banking Personnel Selection',
      short_name: 'IBPS',
      slug: 'ibps',
      official_domain: 'ibps.in',
      description: 'Autonomous agency for recruitment of officers and clerks in Public Sector Banks in India.',
      org_type: 'recruitment',
      official_portal_url: 'https://ibps.in',
      helpline_number: '1800-222-366',
      contact_email: 'ibpso@ibps.in',
      is_verified: true,
    },
    {
      name: 'Railway Recruitment Control Board',
      short_name: 'RRB',
      slug: 'rrb',
      official_domain: 'rrbcdg.gov.in',
      description: 'Government organization in India under Ministry of Railways for appointment of railway personnel.',
      org_type: 'recruitment',
      official_portal_url: 'https://indianrailways.gov.in',
      helpline_number: '0172-2730093',
      contact_email: 'rrb-chandigarh@nic.in',
      is_verified: true,
    },
    {
      name: 'National Scholarship Portal',
      short_name: 'NSP',
      slug: 'nsp',
      official_domain: 'scholarships.gov.in',
      description: 'Mission Mode Project under Digital India to provide common electronic portal for scholarships given by Central & State governments.',
      org_type: 'scholarship_body',
      official_portal_url: 'https://scholarships.gov.in',
      helpline_number: '0120-6619540',
      contact_email: 'helpdesk@nsp.gov.in',
      is_verified: true,
    },
    {
      name: 'Consortium of National Law Universities',
      short_name: 'NLUs',
      slug: 'consortium-of-nlus',
      official_domain: 'consortiumofnlus.ac.in',
      description: 'Governing consortium for admissions into 24 participating National Law Universities across India.',
      org_type: 'university',
      official_portal_url: 'https://consortiumofnlus.ac.in',
      helpline_number: '080-47162020',
      contact_email: 'clat@consortiumofnlus.ac.in',
      is_verified: true,
    },
    {
      name: 'Indian Institute of Management',
      short_name: 'IIMs',
      slug: 'iim-cat',
      official_domain: 'iimcat.ac.in',
      description: 'Premier management institutes in India conducting the Common Admission Test (CAT).',
      org_type: 'university',
      official_portal_url: 'https://iimcat.ac.in',
      helpline_number: '1800-210-8720',
      contact_email: 'cathelpdesk@iimcat.ac.in',
      is_verified: true,
    },
    {
      name: 'Indian Space Research Organisation',
      short_name: 'ISRO',
      slug: 'isro',
      official_domain: 'isro.gov.in',
      description: 'National space agency of India providing educational fellowships, internships, and YUVIKA programmes for students.',
      org_type: 'national_testing',
      official_portal_url: 'https://isro.gov.in',
      helpline_number: '080-22172294',
      contact_email: 'yuvika@isro.gov.in',
      is_verified: true,
    },
    {
      name: 'NITI Aayog (National Institution for Transforming India)',
      short_name: 'NITI Aayog',
      slug: 'niti-aayog',
      official_domain: 'niti.gov.in',
      description: 'Apex public policy think tank of the Government of India providing strategic and technical advice.',
      org_type: 'commission',
      official_portal_url: 'https://niti.gov.in',
      helpline_number: '011-23096620',
      contact_email: 'internship-niti@gov.in',
      is_verified: true,
    },
    {
      name: 'Ministry of External Affairs',
      short_name: 'MEA',
      slug: 'mea',
      official_domain: 'mea.gov.in',
      description: 'Government agency responsible for conducting foreign relations of India.',
      org_type: 'commission',
      official_portal_url: 'https://mea.gov.in',
      helpline_number: '011-24676555',
      contact_email: 'internship@mea.gov.in',
      is_verified: true,
    },
    {
      name: 'Reserve Bank of India',
      short_name: 'RBI',
      slug: 'rbi',
      official_domain: 'rbi.org.in',
      description: 'Central bank and regulatory body responsible for regulation of the Indian banking system.',
      org_type: 'recruitment',
      official_portal_url: 'https://rbi.org.in',
      helpline_number: '022-22601000',
      contact_email: 'helpdesk@rbi.org.in',
      is_verified: true,
    },
    {
      name: 'State Bank of India',
      short_name: 'SBI',
      slug: 'sbi',
      official_domain: 'sbi.co.in',
      description: 'Indian multinational public sector bank and financial services statutory body.',
      org_type: 'recruitment',
      official_portal_url: 'https://sbi.co.in/careers',
      helpline_number: '1800-1234',
      contact_email: 'careers@sbi.co.in',
      is_verified: true,
    },
    {
      name: 'GATE Organizing Committee',
      short_name: 'GATE',
      slug: 'gate-committee',
      official_domain: 'gate.iitr.ac.in',
      description: 'National committee of IITs and IISc administering the Graduate Aptitude Test in Engineering.',
      org_type: 'national_testing',
      official_portal_url: 'https://gate.iitr.ac.in',
      helpline_number: '01332-284531',
      contact_email: 'gate@iitr.ac.in',
      is_verified: true,
    },
    {
      name: 'Uttar Pradesh Public Service Commission',
      short_name: 'UPPSC',
      slug: 'uppsc',
      official_domain: 'uppsc.up.nic.in',
      description: 'State agency authorized to conduct the Civil Services Examination for Uttar Pradesh.',
      org_type: 'commission',
      official_portal_url: 'https://uppsc.up.nic.in',
      helpline_number: '0532-2407215',
      contact_email: 'online.uppsc@nic.in',
      is_verified: true,
    },
    {
      name: 'Bihar Public Service Commission',
      short_name: 'BPSC',
      slug: 'bpsc',
      official_domain: 'bpsc.bih.nic.in',
      description: 'State recruitment commission for selecting candidates for civil services of Bihar.',
      org_type: 'commission',
      official_portal_url: 'https://bpsc.bih.nic.in',
      helpline_number: '0612-2215751',
      contact_email: 'bpscpat-bih@nic.in',
      is_verified: true,
    },
    {
      name: 'Defence Research and Development Organisation',
      short_name: 'DRDO',
      slug: 'drdo',
      official_domain: 'drdo.gov.in',
      description: 'Premier agency under the Ministry of Defence charged with military research and development.',
      org_type: 'national_testing',
      official_portal_url: 'https://drdo.gov.in',
      helpline_number: '011-23818629',
      contact_email: 'director.rac@gov.in',
      is_verified: true,
    },
    {
      name: 'Parliament of India',
      short_name: 'Sansad',
      slug: 'parliament-of-india',
      official_domain: 'sansad.in',
      description: 'Supreme legislative body of the Republic of India comprising the Lok Sabha and Rajya Sabha.',
      org_type: 'commission',
      official_portal_url: 'https://sansad.in',
      helpline_number: '011-23034000',
      contact_email: 'pdp.loksabha@sansad.nic.in',
      is_verified: true,
    }
  ];

  const users = [
    {
      email: 'admin@examsetu.in',
      password_hash: adminPasswordHash,
      full_name: 'Kuldeep Sharma (Chief Administrator)',
      role: 'admin',
      email_verified: true,
    },
    {
      email: 'verifier@examsetu.in',
      password_hash: verifierPasswordHash,
      full_name: 'Priya Verma (Senior Data Verifier)',
      role: 'verifier',
      email_verified: true,
    },
    {
      email: 'student@examsetu.in',
      password_hash: studentPasswordHash,
      full_name: 'Aarav Patel',
      role: 'student',
      email_verified: true,
      profile: {
        class_level: '12',
        board: 'CBSE',
        state: 'Madhya Pradesh',
        stream: 'PCB',
        subjects: ['Physics', 'Chemistry', 'Biology', 'English'],
        target_exams: ['NEET UG', 'CUET UG', 'MP Board 12th'],
        career_interests: ['Medicine', 'Biotechnology', 'Allied Health Sciences'],
      }
    }
  ];

  return { states, categories, organizations, users };
}
