import { query } from '../src/lib/db';

export async function seedEducationEcosystem() {
  console.log('--- Starting Comprehensive Education Ecosystem Seeding ---');

  // 1. Seed Boards (Central + Major States)
  const boardsData = [
    {
      name: 'Central Board of Secondary Education',
      short_name: 'CBSE',
      slug: 'cbse',
      board_type: 'central',
      state_name: 'All India',
      official_website: 'https://www.cbse.gov.in',
      official_domain: 'cbse.gov.in',
      classes_covered: ['10th', '12th'],
      grading_system: '9-point grading system (A1 to E2)',
      supplementary_exam_name: 'CBSE Supplementary / Compartment Examination',
      revaluation_process_info: 'Three-tier verification: 1. Verification of Marks, 2. Obtaining Photocopy of Evaluated Answer Book, 3. Re-evaluation of specific questions.',
      pattern_summary: 'Competency-based questions (50%), Objective/MCQ (20%), Short/Long descriptive (30%). Internal assessment carries 20 marks.',
      practical_exam_info: 'Practicals carry 30 marks in Physics, Chemistry, Biology, Computer Science. External examiner appointed by CBSE.',
      helpline_number: '1800-11-8002',
    },
    {
      name: 'Council for the Indian School Certificate Examinations',
      short_name: 'CISCE',
      slug: 'cisce',
      board_type: 'central',
      state_name: 'All India',
      official_website: 'https://cisce.org',
      official_domain: 'cisce.org',
      classes_covered: ['10th (ICSE)', '12th (ISC)'],
      grading_system: 'Grade scale 1 to 9 (1-7 pass, 8-9 fail)',
      supplementary_exam_name: 'CISCE Improvement / Compartment Examination',
      revaluation_process_info: 'Online recheck application through CISCE Service Portal within prescribed window post-results.',
      pattern_summary: 'Comprehensive continuous evaluation with 80% theory and 20% internal assessment for ICSE.',
      practical_exam_info: 'ISC Class 12 includes rigorous 3-hour practical examinations and viva-voce.',
      helpline_number: '011-26413820',
    },
    {
      name: 'National Institute of Open Schooling',
      short_name: 'NIOS',
      slug: 'nios',
      board_type: 'open',
      state_name: 'All India',
      official_website: 'https://www.nios.ac.in',
      official_domain: 'nios.ac.in',
      classes_covered: ['Secondary (10th)', 'Senior Secondary (12th)'],
      grading_system: 'Grades A to E with 5-subject minimum passing criterion',
      supplementary_exam_name: 'NIOS On-Demand Examination (ODE) & Public Exams (April/Oct)',
      revaluation_process_info: 'Online scrutiny and re-evaluation facility on NIOS Student Portal.',
      pattern_summary: 'Tutor Marked Assignments (TMA) 20% weightage, Public Examination 80%. Flexible On-Demand testing available.',
      practical_exam_info: 'Personal Contact Programmes (PCP) and practical exams held at accredited study centers.',
      helpline_number: '1800-180-9393',
    },
    {
      name: 'Uttar Pradesh Madhyamik Shiksha Parishad',
      short_name: 'UPMSP',
      slug: 'upmsp',
      board_type: 'state',
      state_name: 'Uttar Pradesh',
      official_website: 'https://upmsp.edu.in',
      official_domain: 'upmsp.edu.in',
      classes_covered: ['10th (High School)', '12th (Intermediate)'],
      grading_system: 'Numerical marks with letter grades',
      supplementary_exam_name: 'UPMSP High School / Intermediate Compartment Examination',
      revaluation_process_info: 'Scrutiny application through official portal within 30 days of result declaration.',
      pattern_summary: '70% Theory + 30% Project/Internal assessment for Class 10; 70/30 theory-practical for Science Class 12.',
      practical_exam_info: 'CCTV-monitored practical examinations with external examiners appointed by the Board.',
      helpline_number: '1800-180-5310',
    },
    {
      name: 'Madhya Pradesh Board of Secondary Education',
      short_name: 'MPBSE',
      slug: 'mpbse',
      board_type: 'state',
      state_name: 'Madhya Pradesh',
      official_website: 'https://mpbse.nic.in',
      official_domain: 'mpbse.nic.in',
      classes_covered: ['10th (HSC)', '12th (HSSC)'],
      grading_system: 'Numerical marks (Distinction >=75%, 1st Div >=60%)',
      supplementary_exam_name: 'MPBSE Supplementary Examination & Ruk Jana Nahi Yojana',
      revaluation_process_info: 'Retotaling and Answer Copy photocopy request via MPOnline portal within 15 days.',
      pattern_summary: '75 marks theory + 25 marks project/practical for high school.',
      practical_exam_info: 'Conducted at school level under board-appointed observers.',
      helpline_number: '0755-2570248',
    },
    {
      name: 'Bihar School Examination Board',
      short_name: 'BSEB',
      slug: 'bseb',
      board_type: 'state',
      state_name: 'Bihar',
      official_website: 'https://biharboardonline.bihar.gov.in',
      official_domain: 'biharboardonline.bihar.gov.in',
      classes_covered: ['10th (Matric)', '12th (Inter)'],
      grading_system: 'Division system (1st, 2nd, 3rd Division)',
      supplementary_exam_name: 'BSEB Matric / Inter Compartmental-cum-Special Exam',
      revaluation_process_info: 'Scrutiny module on biharboardonline.bihar.gov.in.',
      pattern_summary: '50% OMR-based Objective MCQs + 50% Subjective questions with 100% internal options.',
      practical_exam_info: 'Held annually in January at designated district centers.',
      helpline_number: '0612-2232074',
    },
    {
      name: 'Maharashtra State Board of Secondary and Higher Secondary Education',
      short_name: 'MSBSHSE',
      slug: 'msbshse',
      board_type: 'state',
      state_name: 'Maharashtra',
      official_website: 'https://mahahsscboard.in',
      official_domain: 'mahahsscboard.in',
      classes_covered: ['10th (SSC)', '12th (HSC)'],
      grading_system: 'Percentage-based Distinction/1st/2nd Class',
      supplementary_exam_name: 'HSC / SSC July-August Supplementary Exam',
      revaluation_process_info: 'Online verification of marks and answer-book photocopy via verification.mh-ssc.ac.in.',
      pattern_summary: '80 marks theory + 20 marks internal/practical for non-science; 70 theory + 30 practical for science.',
      practical_exam_info: 'Conducted in February across 9 Divisional Boards (Pune, Mumbai, Nagpur, etc.).',
      helpline_number: '020-25705301',
    },
    {
      name: 'Board of Secondary Education Rajasthan',
      short_name: 'RBSE',
      slug: 'rbse',
      board_type: 'state',
      state_name: 'Rajasthan',
      official_website: 'https://rajeduboard.rajasthan.gov.in',
      official_domain: 'rajasthan.gov.in',
      classes_covered: ['Secondary (10th)', 'Senior Secondary (12th)'],
      grading_system: 'Marks and Division system',
      supplementary_exam_name: 'RBSE Supplementary Examination',
      revaluation_process_info: 'Scrutiny application through school/nodal portal.',
      pattern_summary: '80% board exam + 20% sessional marks sent by schools.',
      practical_exam_info: 'Conducted in January-February by board-appointed external examiners.',
      helpline_number: '0145-2632866',
    },
    {
      name: 'Gujarat Secondary and Higher Secondary Education Board',
      short_name: 'GSEB',
      slug: 'gseb',
      board_type: 'state',
      state_name: 'Gujarat',
      official_website: 'https://www.gseb.org',
      official_domain: 'gseb.org',
      classes_covered: ['10th (SSC)', '12th (HSC Science/General)'],
      grading_system: 'Percentile rank and grades A1 to E2',
      supplementary_exam_name: 'GSEB Purak Pariksha (Supplementary Exam)',
      revaluation_process_info: 'Rechecking and re-evaluation via gseb.org.',
      pattern_summary: '50% MCQs (Part A) + 50% Descriptive (Part B) for Science stream.',
      practical_exam_info: 'State-wide standardized practical exams for Physics, Chemistry, Biology.',
      helpline_number: '1800-233-5500',
    },
    {
      name: 'West Bengal Council of Higher Secondary Education & WBBSE',
      short_name: 'WBCHSE',
      slug: 'wbchse',
      board_type: 'state',
      state_name: 'West Bengal',
      official_website: 'https://wbchse.wb.gov.in',
      official_domain: 'wbchse.wb.gov.in',
      classes_covered: ['10th (Madhyamik)', '12th (Higher Secondary)'],
      grading_system: 'Grades O, A+, A, B+, B, C, D',
      supplementary_exam_name: 'WB HS Supplementary Examination',
      revaluation_process_info: 'Post Publication Scrutiny (PPS) & Post Publication Review (PPR).',
      pattern_summary: 'Semester system implementation underway under NEP 2020 guidelines.',
      practical_exam_info: 'Held in December-January at respective higher secondary institutions.',
      helpline_number: '033-23379661',
    },
  ];

  for (const b of boardsData) {
    await query(
      `INSERT INTO boards (
        name, short_name, slug, board_type, state_name, official_website,
        official_domain, classes_covered, grading_system, supplementary_exam_name,
        revaluation_process_info, pattern_summary, practical_exam_info, helpline_number,
        is_verified, last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, true, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        official_website = EXCLUDED.official_website,
        official_domain = EXCLUDED.official_domain,
        pattern_summary = EXCLUDED.pattern_summary,
        last_verified_at = NOW()`,
      [
        b.name,
        b.short_name,
        b.slug,
        b.board_type,
        b.state_name,
        b.official_website,
        b.official_domain,
        JSON.stringify(b.classes_covered),
        b.grading_system,
        b.supplementary_exam_name,
        b.revaluation_process_info,
        b.pattern_summary,
        b.practical_exam_info,
        b.helpline_number,
      ]
    );
  }
  console.log(`Seeded ${boardsData.length} Education Boards.`);

  // 2. Seed Counselling Authorities
  const counsellingAuthoritiesData = [
    {
      name: 'Joint Seat Allocation Authority',
      short_name: 'JoSAA',
      slug: 'josaa',
      stream: 'Engineering',
      jurisdiction: 'All India (100% IITs, NITs, IIITs & GFTIs)',
      conducting_body: 'Joint collaboration of IITs & CSAB/NITs',
      official_website: 'https://josaa.nic.in',
      official_domain: 'josaa.nic.in',
      description: 'Conducts centralized online counselling for admission to 23 IITs, 32 NITs, 26 IIITs, and 40 GFTIs based on JEE Main and JEE Advanced ranks.',
      helpline_number: '044-22578200',
      contact_email: 'josaa@iitm.ac.in',
    },
    {
      name: 'Central Seat Allocation Board',
      short_name: 'CSAB',
      slug: 'csab',
      stream: 'Engineering',
      jurisdiction: 'NIT+ System Special Rounds & Supernumerary Seats',
      conducting_body: 'Ministry of Education, Govt of India',
      official_website: 'https://csab.nic.in',
      official_domain: 'csab.nic.in',
      description: 'Conducts special counselling rounds to fill vacant seats in NITs, IIITs, and GFTIs after the conclusion of JoSAA rounds.',
      helpline_number: '0755-4051000',
      contact_email: 'csab2026@manit.ac.in',
    },
    {
      name: 'Medical Counselling Committee',
      short_name: 'MCC',
      slug: 'mcc',
      stream: 'Medical',
      jurisdiction: '15% All India Quota, 100% Deemed/Central Universities, AIIMS, JIPMER, AFMC, ESIC',
      conducting_body: 'Directorate General of Health Services (DGHS), MoHFW',
      official_website: 'https://mcc.nic.in',
      official_domain: 'mcc.nic.in',
      description: 'Conducts national counselling for MBBS, BDS, and B.Sc Nursing seats across AIIMS, JIPMER, Central Universities (DU, BHU, AMU), Deemed Universities, and 15% AIQ seats in state government medical colleges.',
      helpline_number: '1800-102-7637',
      contact_email: 'mcc.dghs@gov.in',
    },
    {
      name: 'Ayush Admissions Central Counseling Committee',
      short_name: 'AACCC',
      slug: 'aaccc',
      stream: 'AYUSH',
      jurisdiction: '15% All India Quota, Central Universities & National Institutes',
      conducting_body: 'Ministry of Ayush, Govt of India',
      official_website: 'https://aaccc.gov.in',
      official_domain: 'aaccc.gov.in',
      description: 'Conducts centralized counselling for BAMS, BHMS, BUMS, and BSMS undergraduate and postgraduate seats across India based on NEET scores.',
      helpline_number: '011-29871100',
      contact_email: 'counseling-aaccc@gov.in',
    },
    {
      name: 'Veterinary Council of India',
      short_name: 'VCI',
      slug: 'vci',
      stream: 'Veterinary',
      jurisdiction: '15% All India Quota in Recognized Veterinary Colleges',
      conducting_body: 'Department of Animal Husbandry and Dairying, Govt of India',
      official_website: 'https://vci.dadf.gov.in',
      official_domain: 'vci.dadf.gov.in',
      description: 'Conducts online seat allocation for 15% All India Quota seats in Bachelor of Veterinary Science & Animal Husbandry (B.V.Sc & A.H.) using NEET UG merit.',
      helpline_number: '011-26184149',
      contact_email: 'vciinfo@nic.in',
    },
    {
      name: 'Consortium of NLUs Centralized Admission',
      short_name: 'Consortium Counselling',
      slug: 'consortium-nlu-counselling',
      stream: 'Law',
      jurisdiction: '24 Participating National Law Universities',
      conducting_body: 'Consortium of National Law Universities',
      official_website: 'https://consortiumofnlus.ac.in',
      official_domain: 'consortiumofnlus.ac.in',
      description: 'Conducts multi-round centralized online counselling and seat allotment for 5-year integrated BA LLB/BBA LLB and 1-year LLM programs at premier NLUs.',
      helpline_number: '080-47162020',
      contact_email: 'clat@consortiumofnlus.ac.in',
    },
    {
      name: 'Centralized Counselling for M.Tech / M.Arch / M.Plan',
      short_name: 'CCMT',
      slug: 'ccmt',
      stream: 'Engineering (PG)',
      jurisdiction: 'NITs, IIITs, IIEST Shibpur, and Participating GFTIs',
      conducting_body: 'Designated Coordinating NIT / MoE',
      official_website: 'https://ccmt.admissions.nic.in',
      official_domain: 'ccmt.admissions.nic.in',
      description: 'Conducts centralized seat allocation for postgraduate engineering and architecture programs based on valid GATE scores.',
      helpline_number: '044-22578000',
      contact_email: 'helpdesk.ccmt@admissions.nic.in',
    },
    {
      name: 'IIM Common Admission Process',
      short_name: 'IIM CAP',
      slug: 'iim-cap',
      stream: 'Management (PG)',
      jurisdiction: 'Participating New & Baby IIMs (9+ IIMs)',
      conducting_body: 'Coordinating IIM for the Academic Year',
      official_website: 'https://iimcat.ac.in',
      official_domain: 'iimcat.ac.in',
      description: 'Conducts combined Personal Interview (PI) and merit score calculation for several premier Indian Institutes of Management based on CAT percentiles.',
      helpline_number: '1800-266-4074',
      contact_email: 'cathelpdesk@iimcat.ac.in',
    },
    {
      name: 'Madhya Pradesh Directorate of Technical Education',
      short_name: 'MP DTE',
      slug: 'mp-dte',
      stream: 'Engineering (State)',
      jurisdiction: 'Madhya Pradesh State Govt & Private Engineering Colleges',
      conducting_body: 'Department of Technical Education, Govt of MP',
      official_website: 'https://dte.mponline.gov.in',
      official_domain: 'mponline.gov.in',
      description: 'Conducts centralized counselling for B.Tech, MCA, MBA, and Diploma seats in MP based on JEE Main and qualifying exam scores.',
      helpline_number: '0755-6720200',
      contact_email: 'dtemponline@mp.gov.in',
    },
    {
      name: 'Maharashtra State Common Entrance Test Cell',
      short_name: 'MHT CET Cell',
      slug: 'mht-cet-cell',
      stream: 'State-Combined',
      jurisdiction: 'Maharashtra State Quota & All India Seats',
      conducting_body: 'Government of Maharashtra',
      official_website: 'https://cetcell.mahacet.org',
      official_domain: 'mahacet.org',
      description: 'Conducts Centralized Admission Process (CAP Rounds) for Engineering, Pharmacy, Agriculture, Law, and Architecture programs across Maharashtra.',
      helpline_number: '022-22016157',
      contact_email: 'cetcell@mahacet.org',
    },
  ];

  const authMap = new Map<string, string>();
  for (const ca of counsellingAuthoritiesData) {
    const res = await query(
      `INSERT INTO counselling_authorities (
        name, short_name, slug, stream, jurisdiction, conducting_body,
        official_website, official_domain, description, helpline_number, contact_email,
        is_verified, last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, true, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        official_website = EXCLUDED.official_website,
        official_domain = EXCLUDED.official_domain,
        description = EXCLUDED.description,
        last_verified_at = NOW()
      RETURNING id, slug`,
      [
        ca.name,
        ca.short_name,
        ca.slug,
        ca.stream,
        ca.jurisdiction,
        ca.conducting_body,
        ca.official_website,
        ca.official_domain,
        ca.description,
        ca.helpline_number,
        ca.contact_email,
      ]
    );
    authMap.set(ca.slug, res.rows[0].id);
  }
  console.log(`Seeded ${counsellingAuthoritiesData.length} Counselling Authorities.`);

  // 3. Seed Counselling Processes
  const josaaId = authMap.get('josaa');
  const mccId = authMap.get('mcc');
  const nluCounsellingId = authMap.get('consortium-nlu-counselling');

  const processesData = [
    {
      authority_id: josaaId,
      title: 'JoSAA Centralized Engineering Seat Allocation 2026-27',
      slug: 'josaa-counselling-2026',
      cycle_year: 2026,
      official_portal_url: 'https://josaa.nic.in',
      notification_url: 'https://josaa.nic.in/business-rules/',
      process_overview: 'Centralized counselling for 23 IITs, 32 NITs, 26 IIITs, and 40 GFTIs. Candidates register with JEE Main application number and fill preferences in order of choice priority.',
      eligibility_summary: 'JEE Main rank for NIT+/IIIT/GFTI systems and JEE Advanced qualifying rank for IIT system. Minimum 75% in Class 12 (65% for SC/ST/PwD) or top 20 percentile.',
      reservation_summary: 'GEN-EWS: 10%, OBC-NCL: 27%, SC: 15%, ST: 7.5%, PwD: 5% horizontal in each category. Supernumerary female seats (minimum 20% female enrollment).',
      rounds_structure: [
        {
          round_number: 1,
          name: 'Round 1 Seat Allotment',
          description: 'Initial allocation based on candidate priority choice list and All India Ranks.',
          status: 'unannounced',
          rules_summary: 'Candidate options: Freeze (Accept & Exit), Slide (Accept & Upgrade within same Institute), Float (Accept & Upgrade to any higher preference Institute). Seat Acceptance Fee (SAF) mandatory.',
        },
        {
          round_number: 2,
          name: 'Round 2 Seat Allotment',
          description: 'Upgradation round for float and slide candidates with fresh allotments for unallocated candidates.',
          status: 'unannounced',
          rules_summary: 'Online reporting, document verification query response, withdrawal option opens.',
        },
        {
          round_number: 3,
          name: 'Round 3 Seat Allotment',
          description: 'Subsequent allocation and vacancy reconciliation.',
          status: 'unannounced',
          rules_summary: 'Upgradation and seat withdrawal window.',
        },
        {
          round_number: 4,
          name: 'Round 4 Seat Allotment',
          description: 'Category reconciliation and vacancy progression.',
          status: 'unannounced',
          rules_summary: 'Strict deadline for withdrawal of allocated seats.',
        },
        {
          round_number: 5,
          name: 'Round 5 Seat Allotment',
          description: 'Penultimate round for IIT system.',
          status: 'unannounced',
          rules_summary: 'Last round for IIT seat withdrawal.',
        },
        {
          round_number: 6,
          name: 'Round 6 Final JoSAA Allotment',
          description: 'Final allocation round for IITs. Unfilled seats in NIT+ system transferred to CSAB Special Rounds.',
          status: 'unannounced',
          rules_summary: 'Mandatory Partial Admission Fee (PAF) payment for NIT+ candidates to confirm admission.',
        },
      ],
      step_by_step_process: [
        {
          step: 1,
          title: 'Online Registration',
          description: 'Log in with JEE Main credentials on josaa.nic.in and verify contact details.',
          action_required: 'No registration fee charged for JoSAA participation.',
        },
        {
          step: 2,
          title: 'Choice Filling & Ordering',
          description: 'Fill all eligible engineering branches and institutes in descending order of personal preference.',
          action_required: 'Fill maximum valid choices; unselected programs cannot be allotted.',
        },
        {
          step: 3,
          title: 'Choice Locking',
          description: 'Lock choices before the announced deadline. Unlocked choices automatically lock at the cutoff timestamp.',
          action_required: 'Take a printout of locked choices for future reference.',
        },
        {
          step: 4,
          title: 'Seat Allocation Result',
          description: 'Check allotment status in each round. If allotted, download Provisional Seat Allotment Letter.',
          action_required: 'Select Willingness: Freeze, Float, or Slide.',
        },
        {
          step: 5,
          title: 'Seat Acceptance Fee & Document Upload',
          description: 'Upload Class 10 Certificate (DoB), Class 12 Marks Sheet, Category Certificate (OBC-NCL/EWS/SC/ST), PwD Certificate (if applicable), and Medical Certificate.',
          action_required: 'Pay Seat Acceptance Fee (SAF: ₹35,000 for Gen/OBC, ₹17,500 for SC/ST/PwD).',
        },
        {
          step: 6,
          title: 'Online Query Resolution & Document Verification',
          description: 'Virtual reporting center verifies documents online and raises queries if clarifications are needed.',
          action_required: 'Respond to queries within 24 hours to prevent seat cancellation.',
        },
        {
          step: 7,
          title: 'Physical Reporting at Allotted Institute',
          description: 'After Round 6 / CSAB, report to the allotted IIT/NIT with original documents for physical verification and commencement of classes.',
          action_required: 'Complete institute admission formalities and balance fee payment.',
        },
      ],
      required_documents: [
        'Provisional Seat Allotment Letter',
        'Class 10 Certificate / Birth Certificate (Date of Birth proof)',
        'Class 12 / Qualifying Exam Mark Sheet and Passing Certificate',
        'JEE Main / JEE Advanced Admit Card & Scorecard',
        'Category Certificate (GEN-EWS / OBC-NCL issued on or after official cut-off date)',
        'SC / ST Certificate (Central Govt format)',
        'PwD Disability Certificate from Authorized Medical Board (if applicable)',
        'Medical Fitness Certificate in JoSAA Prescribed Format (Annexure 7)',
        'Government Issued Photo ID (Aadhaar / Passport / Voter ID)',
        'Passport Size Photographs (identical to JEE application)',
      ],
      seat_matrix_info: 'Over 60,000+ seats across 23 IITs (approx 17,500), 32 NITs (approx 24,000), 26 IIITs (approx 8,500), and 40 GFTIs.',
      fees_info: 'Seat Acceptance Fee: ₹35,000 (GEN/OBC/EWS) / ₹17,500 (SC/ST/PwD). Adjusted against 1st semester college tuition.',
      status: 'upcoming',
    },
    {
      authority_id: mccId,
      title: 'MCC NEET UG National Medical Counselling 2026-27',
      slug: 'mcc-neet-ug-counselling-2026',
      cycle_year: 2026,
      official_portal_url: 'https://mcc.nic.in',
      notification_url: 'https://mcc.nic.in/ug-medical-counselling/',
      process_overview: 'Online counselling conducted by Medical Counselling Committee (DGHS) for 15% AIQ seats in Govt Medical/Dental Colleges, 100% seats in AIIMS, JIPMER, Central Universities (AMU, BHU, DU), Deemed Universities, and B.Sc Nursing in Central Institutes.',
      eligibility_summary: 'Candidates qualifying NEET (UG) with minimum 50th percentile (UR/EWS) or 40th percentile (SC/ST/OBC) and 50% in Class 12 Physics, Chemistry, Biology.',
      reservation_summary: 'SC: 15%, ST: 7.5%, OBC-NCL: 27%, EWS: 10%, PwD: 5% horizontal in AIQ seats.',
      rounds_structure: [
        {
          round_number: 1,
          name: 'Round 1 (AIQ & Deemed/Central)',
          description: 'Registration, choice filling, and first seat allocation.',
          status: 'unannounced',
          rules_summary: 'Free Exit available (candidate can choose not to join without forfeiting security deposit). Upgradation to Round 2 can be opted at college reporting.',
        },
        {
          round_number: 2,
          name: 'Round 2 Allotment',
          description: 'Fresh registration opens for new candidates; choices unlocked for registered candidates.',
          status: 'unannounced',
          rules_summary: 'Exit with Forfeiture available (security deposit forfeited if allotted but candidate does not join). Joined candidates can seek upgradation to Round 3.',
        },
        {
          round_number: 3,
          name: 'Round 3 (Mop-Up Round)',
          description: 'Fresh registration for vacant seats.',
          status: 'unannounced',
          rules_summary: 'No seat exit allowed after joining Round 3. Candidates who join Round 3 are ineligible for any further state or central counselling.',
        },
        {
          round_number: 4,
          name: 'Stray Vacancy Round (Online Centralized)',
          description: 'Strictly online centralized round conducted by MCC for remaining vacant seats.',
          status: 'unannounced',
          rules_summary: 'No fresh registration. Only unallotted registered candidates considered. Candidates allotted a seat must join; refusal leads to debarment from NEET for 1 year.',
        },
      ],
      step_by_step_process: [
        {
          step: 1,
          title: 'MCC Portal Registration',
          description: 'Register with NEET Roll Number and Application Number on mcc.nic.in and pay non-refundable registration fee + refundable security deposit.',
          action_required: 'Pay ₹1,000 (AIQ Gen) or ₹500 (SC/ST) + ₹10,000 security deposit (or ₹5,000 for SC/ST, ₹2,00,000 for Deemed Universities).',
        },
        {
          step: 2,
          title: 'Choice Filling & Priority Selection',
          description: 'Select medical and dental colleges across India in preferred priority order.',
          action_required: 'Lock choices during the designated window.',
        },
        {
          step: 3,
          title: 'Provisional & Final Seat Allotment',
          description: 'MCC processes choices based on AIR and releases allotment result and downloadable allotment letter.',
          action_required: 'Download Provisional Allotment Letter.',
        },
        {
          step: 4,
          title: 'Reporting to Allotted Medical College',
          description: 'Physically report to the college within the allotted window (approx 5-7 days) with original documents and college fees.',
          action_required: 'Undergo physical document verification and medical fitness examination.',
        },
      ],
      required_documents: [
        'NEET UG Admit Card & Rank Card (Scorecard)',
        'MCC Provisional Allotment Letter',
        'Class 10 Certificate & Marksheet (Date of Birth)',
        'Class 12 Certificate & Marksheet',
        'Valid Government Photo ID (Aadhaar / PAN / Passport)',
        'Eight (8) Passport size photographs matching NEET application',
        'Caste / Category Certificate (SC/ST/OBC-NCL in Central format)',
        'EWS Certificate issued by competent revenue authority',
        'PwD Disability Certificate from designated MCC Disability Screening Center',
      ],
      seat_matrix_info: 'Approx 1,10,000+ MBBS seats and 27,000+ BDS seats across government, AIIMS, and private/deemed medical colleges in India.',
      fees_info: 'AIQ Registration: ₹1,000 (UR) / ₹500 (SC/ST) + Security Deposit: ₹10,000 (UR) / ₹5,000 (SC/ST) / ₹2,00,000 (Deemed Universities).',
      status: 'upcoming',
    },
    {
      authority_id: nluCounsellingId,
      title: 'Consortium of NLUs Centralized Admission Counselling 2027',
      slug: 'clat-counselling-2027',
      cycle_year: 2027,
      official_portal_url: 'https://consortiumofnlus.ac.in',
      notification_url: 'https://consortiumofnlus.ac.in/clat-2027/',
      process_overview: 'Online counselling for 5-Year Integrated Law (BA LLB / BBA LLB / B.Sc LLB) and 1-Year LLM across 24 participating National Law Universities.',
      eligibility_summary: 'Candidates with valid CLAT 2027 merit rank invited in cohorts based on reservation categories and rank brackets.',
      reservation_summary: 'State domicile quotas (varies by NLU, 25% to 50%), SC: 15%, ST: 7.5%, OBC, EWS, and Women supernumerary quotas.',
      rounds_structure: [
        {
          round_number: 1,
          name: 'First Allotment List',
          description: 'Release of 1st merit allotment across NLSIU, NALSAR, WBNUJS, NLIU, GNLU, and all member NLUs.',
          status: 'unannounced',
          rules_summary: 'Candidates choose: Freeze (Lock seat), Float (Accept and seek higher NLU in next list), or Exit.',
        },
        {
          round_number: 2,
          name: 'Second Allotment List',
          description: 'Upgradation and seat reallocation.',
          status: 'unannounced',
          rules_summary: 'Fee confirmation window for newly allotted candidates.',
        },
        {
          round_number: 3,
          name: 'Third Allotment List',
          description: 'Third round of seat allocation.',
          status: 'unannounced',
          rules_summary: 'Confirmation and NLU campus fee adjustment.',
        },
        {
          round_number: 4,
          name: 'Fourth & Fifth Allotment Lists',
          description: 'Final centralized allotment rounds followed by institutional vacancy rounds.',
          status: 'unannounced',
          rules_summary: 'Final list release and physical reporting at the allotted NLU.',
        },
      ],
      step_by_step_process: [
        {
          step: 1,
          title: 'Counselling Invitation & Registration',
          description: 'Invited candidates log in to consortiumofnlus.ac.in and pay the non-refundable confirmation deposit.',
          action_required: 'Pay Counselling Fee: ₹30,000 (General) or ₹20,000 (SC/ST/OBC/PwD).',
        },
        {
          step: 2,
          title: 'NLU Preference Re-ordering',
          description: 'Candidates can update their NLU preference ranking prior to the first allotment.',
          action_required: 'Carefully rank top NLUs (NLSIU, NALSAR, NUJS, NLUJ, GNLU, NLIU).',
        },
        {
          step: 3,
          title: 'Seat Allocation & Decision',
          description: 'Select Freeze, Float, or Exit within the specified 48-hour window per list.',
          action_required: 'Pay NLU Confirmation Fee (₹20,000) for Freeze/Float.',
        },
        {
          step: 4,
          title: 'Admission Completion at Allotted NLU',
          description: 'Submit documents and pay remaining annual university fees at the allotted National Law University.',
          action_required: 'Physical verification and commencement of law classes in July.',
        },
      ],
      required_documents: [
        'CLAT 2027 Admit Card & Scorecard',
        'Class 10 Statement of Marks & Passing Certificate (Date of Birth)',
        'Class 12 Marks Sheet (minimum 45% for Gen/OBC, 40% for SC/ST)',
        'Character Certificate / Conduct Certificate from last attended institution',
        'Transfer Certificate (TC) / Migration Certificate',
        'Caste / Category / Domicile Certificate (where applicable)',
        'Government Issued Photo Identity Proof',
      ],
      seat_matrix_info: 'Approx 3,400+ undergraduate seats and 1,500+ postgraduate LLM seats across 24 National Law Universities.',
      fees_info: 'Counselling Registration Fee: ₹30,000 (General) / ₹20,000 (Reserved categories), adjusted in university tuition fee.',
      status: 'upcoming',
    },
  ];

  for (const proc of processesData) {
    if (!proc.authority_id) continue;
    await query(
      `INSERT INTO counselling_processes (
        authority_id, cycle_year, title, slug, official_portal_url, notification_url,
        process_overview, eligibility_summary, reservation_summary, rounds_structure,
        step_by_step_process, required_documents, seat_matrix_info, fees_info, status,
        last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        title = EXCLUDED.title,
        official_portal_url = EXCLUDED.official_portal_url,
        process_overview = EXCLUDED.process_overview,
        eligibility_summary = EXCLUDED.eligibility_summary,
        rounds_structure = EXCLUDED.rounds_structure,
        step_by_step_process = EXCLUDED.step_by_step_process,
        required_documents = EXCLUDED.required_documents,
        last_verified_at = NOW()`,
      [
        proc.authority_id,
        proc.cycle_year,
        proc.title,
        proc.slug,
        proc.official_portal_url,
        proc.notification_url,
        proc.process_overview,
        proc.eligibility_summary,
        proc.reservation_summary,
        JSON.stringify(proc.rounds_structure),
        JSON.stringify(proc.step_by_step_process),
        JSON.stringify(proc.required_documents),
        proc.seat_matrix_info,
        proc.fees_info,
        proc.status,
      ]
    );
  }
  console.log(`Seeded ${processesData.length} Counselling Processes.`);

  // 4. Seed Institutions (Colleges & Universities across India)
  const institutionsData = [
    {
      name: 'Indian Institute of Technology Bombay',
      short_name: 'IIT Bombay',
      slug: 'iit-bombay',
      institution_type: 'IIT',
      state_name: 'Maharashtra',
      city: 'Mumbai',
      official_website: 'https://www.iitb.ac.in',
      affiliation: 'Autonomous Institute of National Importance',
      recognized_by: 'MoE / UGC',
      accepted_exams: ['JEE Advanced', 'GATE', 'UCEED', 'CEED', 'JAM', 'CAT'],
      counselling_authorities: ['JoSAA', 'CCMT'],
      courses_offered: ['B.Tech Computer Science', 'B.Tech Electrical', 'B.Tech Mechanical', 'B.Des', 'M.Tech', 'PhD'],
      campus_overview: 'Premier engineering and research institute situated in Powai, Mumbai. Established in 1958 with UNESCO support.',
    },
    {
      name: 'Indian Institute of Technology Delhi',
      short_name: 'IIT Delhi',
      slug: 'iit-delhi',
      institution_type: 'IIT',
      state_name: 'Delhi',
      city: 'New Delhi',
      official_website: 'https://home.iitd.ac.in',
      affiliation: 'Autonomous Institute of National Importance',
      recognized_by: 'MoE / UGC',
      accepted_exams: ['JEE Advanced', 'GATE', 'UCEED', 'CEED', 'JAM', 'CAT'],
      counselling_authorities: ['JoSAA', 'CCMT'],
      courses_offered: ['B.Tech Computer Science', 'B.Tech Mathematics & Computing', 'B.Tech Electrical', 'B.Des', 'M.Tech', 'MBA', 'PhD'],
      campus_overview: 'Leading technical university located in Hauz Khas, New Delhi. Renowned for top research patents and startup incubators.',
    },
    {
      name: 'Indian Institute of Technology Madras',
      short_name: 'IIT Madras',
      slug: 'iit-madras',
      institution_type: 'IIT',
      state_name: 'Tamil Nadu',
      city: 'Chennai',
      official_website: 'https://www.iitm.ac.in',
      affiliation: 'Autonomous Institute of National Importance',
      recognized_by: 'MoE / UGC',
      accepted_exams: ['JEE Advanced', 'GATE', 'JAM', 'HSEE', 'CAT'],
      counselling_authorities: ['JoSAA', 'CCMT'],
      courses_offered: ['B.Tech Aerospace', 'B.Tech Computer Science', 'B.Tech Naval Architecture', 'M.Tech', 'BS Data Science', 'PhD'],
      campus_overview: 'Ranked #1 overall university in NIRF India rankings. Sprawling green campus adjacent to Guindy National Park.',
    },
    {
      name: 'All India Institute of Medical Sciences New Delhi',
      short_name: 'AIIMS New Delhi',
      slug: 'aiims-new-delhi',
      institution_type: 'AIIMS',
      state_name: 'Delhi',
      city: 'New Delhi',
      official_website: 'https://www.aiims.edu',
      affiliation: 'Autonomous Institute of National Importance under MoHFW',
      recognized_by: 'NMC / MoHFW',
      accepted_exams: ['NEET UG', 'INI CET (PG)', 'INI SS'],
      counselling_authorities: ['MCC (Medical Counselling Committee)', 'AIIMS Examination Section'],
      courses_offered: ['MBBS', 'B.Sc (Hons) Nursing', 'MD / MS', 'DM / MCh', 'PhD'],
      campus_overview: 'Apex medical institute and hospital in India, established in 1956. Leader in clinical care, medical research, and subsidized tertiary healthcare.',
    },
    {
      name: 'All India Institute of Medical Sciences Bhopal',
      short_name: 'AIIMS Bhopal',
      slug: 'aiims-bhopal',
      institution_type: 'AIIMS',
      state_name: 'Madhya Pradesh',
      city: 'Bhopal',
      official_website: 'https://aiimsbhopal.edu.in',
      affiliation: 'Institute of National Importance under PMSSY, MoHFW',
      recognized_by: 'NMC',
      accepted_exams: ['NEET UG', 'INI CET (PG)'],
      counselling_authorities: ['MCC'],
      courses_offered: ['MBBS (125 Seats)', 'B.Sc (Hons) Nursing', 'MD / MS', 'Post-Doctoral Fellowships'],
      campus_overview: 'Premier central healthcare and medical education institution in central India established under Pradhan Mantri Swasthya Suraksha Yojana.',
    },
    {
      name: 'National Law School of India University',
      short_name: 'NLSIU Bengaluru',
      slug: 'nlsiu-bengaluru',
      institution_type: 'NLU',
      state_name: 'Karnataka',
      city: 'Bengaluru',
      official_website: 'https://www.nls.ac.in',
      affiliation: 'Statutory National Law University',
      recognized_by: 'Bar Council of India (BCI) / UGC',
      accepted_exams: ['CLAT UG', 'CLAT PG', 'NLSAT'],
      counselling_authorities: ['Consortium of NLUs Centralized Counselling'],
      courses_offered: ['BA LLB (Hons) (5-Year)', '3-Year LLB (Hons)', 'LLM', 'Master of Public Policy (MPP)', 'PhD in Law'],
      campus_overview: 'The pioneer National Law University in India, consistently ranked #1 law school nationwide in NIRF rankings.',
    },
    {
      name: 'National Academy of Legal Studies and Research',
      short_name: 'NALSAR University of Law',
      slug: 'nalsar-hyderabad',
      institution_type: 'NLU',
      state_name: 'Telangana',
      city: 'Hyderabad',
      official_website: 'https://www.nalsar.ac.in',
      affiliation: 'Statutory National Law University',
      recognized_by: 'BCI / UGC',
      accepted_exams: ['CLAT UG', 'CLAT PG', 'CAT'],
      counselling_authorities: ['Consortium of NLUs Centralized Counselling'],
      courses_offered: ['BA LLB (Hons)', 'LLM', 'MBA', 'Integrated BBA-MBA', 'PhD in Law'],
      campus_overview: 'Premier law and legal research university situated in Shamirpet, Hyderabad.',
    },
    {
      name: 'Indian Institute of Management Ahmedabad',
      short_name: 'IIM Ahmedabad',
      slug: 'iim-ahmedabad',
      institution_type: 'IIM',
      state_name: 'Gujarat',
      city: 'Ahmedabad',
      official_website: 'https://www.iima.ac.in',
      affiliation: 'Autonomous Institute of National Importance under IIM Act',
      recognized_by: 'EQUIS / MoE',
      accepted_exams: ['CAT', 'GMAT', 'GRE'],
      counselling_authorities: ['IIM Ahmedabad Direct Admission / AWT-PI'],
      courses_offered: ['MBA / PGP (2-Year)', 'PGP-FABM (Food & Agri-Business)', 'MBA-PGPX (1-Year Executive)', 'PhD in Management'],
      campus_overview: 'India’s premier management school, established in 1961 with Harvard Business School collaboration. Renowned case-method pedagogy.',
    },
    {
      name: 'Indian Institute of Management Indore',
      short_name: 'IIM Indore',
      slug: 'iim-indore',
      institution_type: 'IIM',
      state_name: 'Madhya Pradesh',
      city: 'Indore',
      official_website: 'https://www.iimidr.ac.in',
      affiliation: 'Institute of National Importance under IIM Act (Triple Crown Accredited: AACSB, AMBA, EQUIS)',
      recognized_by: 'MoE / UGC',
      accepted_exams: ['IPMAT (After 12th)', 'CAT', 'GMAT'],
      counselling_authorities: ['IIM Indore Admissions / IIM CAP'],
      courses_offered: ['Integrated Programme in Management (IPM - 5 Year BBA+MBA)', 'Post Graduate Programme in Management (PGP - MBA)', 'Executive MBA', 'FPM (PhD)'],
      campus_overview: 'Sprawling 193-acre campus situated on Prabandh Shikhar hillock in Indore, Madhya Pradesh. Pioneer of the 5-Year IPM program after Class 12.',
    },
    {
      name: 'National Institute of Technology Tiruchirappalli',
      short_name: 'NIT Trichy',
      slug: 'nit-trichy',
      institution_type: 'NIT',
      state_name: 'Tamil Nadu',
      city: 'Tiruchirappalli',
      official_website: 'https://www.nitt.edu',
      affiliation: 'Autonomous Institute of National Importance',
      recognized_by: 'MoE / AICTE',
      accepted_exams: ['JEE Main', 'GATE', 'NIMCET', 'JAM', 'CAT'],
      counselling_authorities: ['JoSAA', 'CSAB', 'CCMT', 'NIMCET Counselling'],
      courses_offered: ['B.Tech (9 Branches)', 'B.Arch', 'M.Tech', 'MCA', 'MBA', 'M.Sc', 'PhD'],
      campus_overview: 'Consistently ranked #1 among all 32 National Institutes of Technology in India.',
    },
    {
      name: 'Maulana Azad National Institute of Technology',
      short_name: 'MANIT Bhopal',
      slug: 'manit-bhopal',
      institution_type: 'NIT',
      state_name: 'Madhya Pradesh',
      city: 'Bhopal',
      official_website: 'http://www.manit.ac.in',
      affiliation: 'Autonomous Institute of National Importance under NITSER Act',
      recognized_by: 'MoE / AICTE',
      accepted_exams: ['JEE Main', 'GATE', 'NIMCET'],
      counselling_authorities: ['JoSAA', 'CSAB', 'CCMT'],
      courses_offered: ['B.Tech (CSE, ECE, EE, Mech, Civil, Chem, MSME)', 'B.Arch', 'B.Plan', 'M.Tech', 'MCA', 'MBA', 'PhD'],
      campus_overview: 'Established in 1960 across 650 acres in Bhopal. Premier engineering hub in Central India.',
    },
    {
      name: 'University of Delhi',
      short_name: 'Delhi University (DU)',
      slug: 'delhi-university',
      institution_type: 'Central_University',
      state_name: 'Delhi',
      city: 'New Delhi',
      official_website: 'https://www.du.ac.in',
      affiliation: 'Collegiate Central University',
      recognized_by: 'UGC / NAAC A++ Grade',
      accepted_exams: ['CUET UG', 'CUET PG', 'CLAT (Faculty of Law)'],
      counselling_authorities: ['DU Common Seat Allocation System (CSAS UG & PG)'],
      courses_offered: ['BA (Hons) in 30+ Subjects', 'B.Com (Hons)', 'B.Sc (Hons)', 'LLB (3-Year)', 'MA', 'M.Com', 'M.Sc', 'PhD'],
      campus_overview: 'One of India’s largest collegiate central universities featuring premier colleges like St. Stephen’s, SRCC, Hindu College, Miranda House, and Lady Shri Ram College.',
    },
  ];

  for (const inst of institutionsData) {
    await query(
      `INSERT INTO institutions (
        name, short_name, slug, institution_type, state_name, city,
        official_website, affiliation, recognized_by, accepted_exams,
        counselling_authorities, courses_offered, campus_overview, is_verified, last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, true, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        official_website = EXCLUDED.official_website,
        accepted_exams = EXCLUDED.accepted_exams,
        counselling_authorities = EXCLUDED.counselling_authorities,
        courses_offered = EXCLUDED.courses_offered,
        last_verified_at = NOW()`,
      [
        inst.name,
        inst.short_name,
        inst.slug,
        inst.institution_type,
        inst.state_name,
        inst.city,
        inst.official_website,
        inst.affiliation,
        inst.recognized_by,
        JSON.stringify(inst.accepted_exams),
        JSON.stringify(inst.counselling_authorities),
        JSON.stringify(inst.courses_offered),
        inst.campus_overview,
      ]
    );
  }
  console.log(`Seeded ${institutionsData.length} Premier Institutions.`);

  // 5. Seed Comprehensive Courses (UG & PG)
  const coursesData = [
    {
      name: 'Bachelor of Technology / Bachelor of Engineering',
      short_name: 'B.Tech / B.E.',
      slug: 'b-tech-engineering',
      degree_level: 'UG',
      stream: 'Engineering',
      duration_years: 4.0,
      eligibility_summary: 'Passed 10+2 with Physics, Mathematics, and one optional subject (Chemistry / Computer Science / Biotechnology) with at least 50-75% aggregate.',
      stream_prerequisites: ['10+2 PCM', 'Polytechnic Diploma in Engineering (Lateral Entry to 2nd Year)'],
      lateral_entry_available: true,
      regulatory_body: 'AICTE',
      accepted_entrance_exams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'MHT CET', 'WBJEE', 'KCET', 'COMEDK', 'VITEEE', 'SRMJEEE', 'GUJCET'],
      counselling_routes: ['JoSAA', 'CSAB', 'State DTE Combined Counselling', 'Institute Spot Rounds'],
      career_scope: 'Software Engineer, Systems Architect, Hardware Design Engineer, Civil/Structural Consultant, Mechanical Plant Engineer, PSU Executive Trainee, Data Scientist, Product Manager.',
      top_specializations: ['Computer Science & Engineering (CSE)', 'Artificial Intelligence & Machine Learning', 'Electronics & Communication (ECE)', 'Electrical Engineering (EE)', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering', 'Aerospace Engineering'],
    },
    {
      name: 'Bachelor of Medicine and Bachelor of Surgery',
      short_name: 'MBBS',
      slug: 'mbbs-medicine',
      degree_level: 'UG',
      stream: 'Medical',
      duration_years: 5.5,
      eligibility_summary: 'Passed 10+2 with Physics, Chemistry, Biology/Biotechnology, and English with minimum 50% aggregate (40% for SC/ST/OBC). Must be at least 17 years old by December 31.',
      stream_prerequisites: ['10+2 PCB / PCMB'],
      lateral_entry_available: false,
      regulatory_body: 'National Medical Commission (NMC)',
      accepted_entrance_exams: ['NEET UG'],
      counselling_routes: ['MCC (15% All India Quota, Central Universities, AIIMS, Deemed)', 'State DME Counselling (85% State Quota)'],
      career_scope: 'Medical Officer, Resident Doctor, Clinical Practitioner, Medical Administrator, Civil Surgeon, Specialist via MD/MS/DNB, Medical Researcher.',
      top_specializations: ['General Medicine', 'General Surgery', 'Pediatrics', 'Obstetrics & Gynecology', 'Orthopedics', 'Anesthesiology', 'Radiology', 'Dermatology'],
    },
    {
      name: 'Bachelor of Dental Surgery',
      short_name: 'BDS',
      slug: 'bds-dental',
      degree_level: 'UG',
      stream: 'Dental',
      duration_years: 5.0,
      eligibility_summary: '10+2 with Physics, Chemistry, Biology and English with minimum 50% marks (40% for SC/ST/OBC) and valid NEET UG qualification.',
      stream_prerequisites: ['10+2 PCB'],
      lateral_entry_available: false,
      regulatory_body: 'Dental Council of India (DCI)',
      accepted_entrance_exams: ['NEET UG'],
      counselling_routes: ['MCC All India Quota', 'State Dental Counselling Authorities'],
      career_scope: 'Dental Surgeon, Orthodontist, Periodontist, Prosthodontist, Maxillofacial Surgeon via MDS, Dental Consultant in Armed Forces (Army Dental Corps).',
      top_specializations: ['Orthodontics', 'Oral & Maxillofacial Surgery', 'Prosthodontics', 'Periodontology', 'Conservative Dentistry & Endodontics'],
    },
    {
      name: 'Bachelor of Ayurvedic Medicine and Surgery',
      short_name: 'BAMS',
      slug: 'bams-ayurveda',
      degree_level: 'UG',
      stream: 'AYUSH',
      duration_years: 5.5,
      eligibility_summary: '10+2 PCB with minimum 50% aggregate (40% for SC/ST/OBC) and NEET UG qualifying score.',
      stream_prerequisites: ['10+2 PCB'],
      lateral_entry_available: false,
      regulatory_body: 'National Commission for Indian System of Medicine (NCISM) / Ministry of Ayush',
      accepted_entrance_exams: ['NEET UG'],
      counselling_routes: ['AACCC Central Counselling', 'State AYUSH Directorate Counselling'],
      career_scope: 'Ayurvedic Medical Officer, Panchakarma Specialist, Research Officer in CCRAS, Wellness Consultant, MD/MS (Ayurveda) specialist.',
      top_specializations: ['Kayachikitsa (Internal Medicine)', 'Shalya Tantra (Surgery)', 'Panchakarma', 'Dravyaguna (Pharmacology)', 'Kaumarbhritya (Pediatrics)'],
    },
    {
      name: 'Bachelor of Pharmacy',
      short_name: 'B.Pharm',
      slug: 'b-pharm-pharmacy',
      degree_level: 'UG',
      stream: 'Pharmacy',
      duration_years: 4.0,
      eligibility_summary: '10+2 with Physics, Chemistry, and either Mathematics or Biology with minimum 50% marks, or Diploma in Pharmacy (D.Pharm) for Lateral Entry into 2nd year.',
      stream_prerequisites: ['10+2 PCM', '10+2 PCB', 'D.Pharm (Lateral Entry)'],
      lateral_entry_available: true,
      regulatory_body: 'Pharmacy Council of India (PCI)',
      accepted_entrance_exams: ['CUET UG', 'MHT CET', 'WBJEE', 'KCET', 'State Pharmacy CETs', 'BITSAT (for B.Pharm)'],
      counselling_routes: ['State Pharmacy Counselling', 'University Central Admissions'],
      career_scope: 'Registered Pharmacist, Drug Inspector (Govt), Formulation Scientist, Quality Assurance (QA/QC) Manager, Regulatory Affairs Specialist, Clinical Research Associate, M.Pharm / GPAT.',
      top_specializations: ['Pharmaceutics', 'Pharmacology', 'Pharmaceutical Chemistry', 'Pharmacognosy', 'Pharmacy Practice'],
    },
    {
      name: 'Bachelor of Science in Nursing',
      short_name: 'B.Sc Nursing',
      slug: 'b-sc-nursing',
      degree_level: 'UG',
      stream: 'Nursing',
      duration_years: 4.0,
      eligibility_summary: '10+2 with Physics, Chemistry, Biology and English with minimum 45% aggregate (40% for SC/ST/OBC). Minimum age 17 years.',
      stream_prerequisites: ['10+2 PCB'],
      lateral_entry_available: false,
      regulatory_body: 'Indian Nursing Council (INC)',
      accepted_entrance_exams: ['NEET UG (for AIIMS/BHU/IPU/Military Nursing)', 'AIIMS B.Sc Nursing Entrance', 'State Nursing CETs (RUHS, JENPAS, MP PNST)'],
      counselling_routes: ['MCC (for Central Institutes)', 'State Nursing Directorate Counselling'],
      career_scope: 'Nursing Officer (NORCET AIIMS), Military Nursing Service (MNS), Clinical Nurse Specialist, ICU/Critical Care Nurse, Hospital Quality Manager, M.Sc Nursing / Nurse Educator.',
      top_specializations: ['Critical Care Nursing', 'Cardiothoracic Nursing', 'Oncology Nursing', 'Pediatric Nursing', 'Community Health Nursing'],
    },
    {
      name: 'Five-Year Integrated Bachelor of Arts & Bachelor of Laws',
      short_name: 'BA LLB (Hons)',
      slug: 'ba-llb-integrated-law',
      degree_level: 'Integrated',
      stream: 'Law',
      duration_years: 5.0,
      eligibility_summary: 'Passed 10+2 in any stream (Science, Commerce, Humanities) with minimum 45% aggregate (40% for SC/ST). No upper age limit as per Supreme Court order.',
      stream_prerequisites: ['10+2 Any Stream (Arts / Commerce / Science)'],
      lateral_entry_available: false,
      regulatory_body: 'Bar Council of India (BCI)',
      accepted_entrance_exams: ['CLAT UG', 'AILET', 'SLAT', 'LSAT India', 'MH CET Law (5-Year)', 'CUET UG'],
      counselling_routes: ['Consortium of NLUs Centralized Counselling', 'State Law CET Cells', 'University Law Admissions'],
      career_scope: 'Advocate / Litigator in High Courts & Supreme Court, Corporate Law Associate in Tier-1 Law Firms, In-house Legal Counsel, Judicial Magistrate / Civil Judge (State Judicial Services), Public Prosecutor, Law Officer in PSUs/Banks (IBPS SO Law, SEBI Grade A Legal).',
      top_specializations: ['Corporate & Commercial Law', 'Constitutional Law', 'Criminal Law & Human Rights', 'Intellectual Property Law (IPR)', 'Cyber Law & Data Protection', 'International Trade & Arbitration'],
    },
    {
      name: 'Bachelor of Business Administration / IPM',
      short_name: 'BBA / IPM',
      slug: 'bba-management',
      degree_level: 'UG',
      stream: 'Management',
      duration_years: 3.0,
      eligibility_summary: 'Passed 10+2 in any stream with minimum 50-60% aggregate marks.',
      stream_prerequisites: ['10+2 Any Stream'],
      lateral_entry_available: false,
      regulatory_body: 'AICTE / UGC',
      accepted_entrance_exams: ['IPMAT (IIM Indore, IIM Rohtak, IIM Ranchi, IIM Jammu, IIM Bodh Gaya)', 'JIPMAT', 'CUET UG', 'SET', 'NMIMS NPAT', 'Christ University Entrance'],
      counselling_routes: ['IIM Selection Interview Rounds', 'University Combined Merit Counselling'],
      career_scope: 'Management Consultant, Business Analyst, Financial Analyst, Marketing Executive, Human Resources Manager, Operations Associate, Fast-track entry into Top MBA.',
      top_specializations: ['Finance & Banking', 'Marketing & Digital Strategy', 'Human Resource Management', 'Business Analytics', 'International Business', 'Supply Chain Management'],
    },
    {
      name: 'Bachelor of Architecture',
      short_name: 'B.Arch',
      slug: 'b-arch-architecture',
      degree_level: 'UG',
      stream: 'Architecture',
      duration_years: 5.0,
      eligibility_summary: '10+2 with Physics, Chemistry, and Mathematics with at least 50% marks in aggregate or 10+3 Diploma with Mathematics. Valid NATA or JEE Main Paper 2 scorecard.',
      stream_prerequisites: ['10+2 with Physics, Chemistry, Maths', '10+3 Diploma with Maths'],
      lateral_entry_available: false,
      regulatory_body: 'Council of Architecture (COA)',
      accepted_entrance_exams: ['NATA', 'JEE Main Paper 2A (B.Arch)', 'AAT (Architecture Aptitude Test for IITs)'],
      counselling_routes: ['JoSAA (for IITs/NITs/SPAs)', 'State Architecture Admissions', 'COA Institutional Counselling'],
      career_scope: 'Registered Architect (COA License), Urban Designer, Landscape Architect, Sustainable Building Consultant, Interior Architect, Heritage Conservationist, Town Planner via M.Plan.',
      top_specializations: ['Sustainable Architecture', 'Urban Design', 'Landscape Architecture', 'Interior Architecture', 'Architectural Conservation'],
    },
    {
      name: 'Master of Technology / Master of Engineering',
      short_name: 'M.Tech / M.E.',
      slug: 'm-tech-postgraduate-engineering',
      degree_level: 'PG',
      stream: 'Engineering',
      duration_years: 2.0,
      eligibility_summary: 'B.Tech/B.E. or equivalent degree in relevant discipline with minimum 60% aggregate marks (or 6.5 CGPA) and a valid GATE score.',
      stream_prerequisites: ['B.Tech / B.E.', 'M.Sc in relevant Science stream (for select disciplines)', 'MCA (for Computer Science disciplines)'],
      lateral_entry_available: false,
      regulatory_body: 'AICTE / MoE',
      accepted_entrance_exams: ['GATE', 'IIT Written Tests / COAP', 'State PGECET'],
      counselling_routes: ['COAP (Common Offer Acceptance Portal for IITs)', 'CCMT (for NITs, IIITs, GFTIs)', 'Direct University Portals'],
      career_scope: 'Senior Research & Development (R&D) Engineer, Chip Design (VLSI) Specialist, AI/ML Research Scientist, Structural Consultant, Aerospace Specialist, Direct progression to PhD / Scientist post at ISRO, DRDO, BARC.',
      top_specializations: ['VLSI Design & Embedded Systems', 'Artificial Intelligence & Machine Learning', 'Thermal & Fluid Engineering', 'Structural Engineering', 'Power Systems & Power Electronics', 'Robotics & Automation'],
    },
    {
      name: 'Doctor of Medicine / Master of Surgery',
      short_name: 'MD / MS',
      slug: 'md-ms-postgraduate-medicine',
      degree_level: 'PG',
      stream: 'Medical',
      duration_years: 3.0,
      eligibility_summary: 'Recognized MBBS degree with completion of 1-year compulsory rotatory internship and permanent/provisional registration with NMC/State Medical Council.',
      stream_prerequisites: ['MBBS with completed 1-Year Internship'],
      lateral_entry_available: false,
      regulatory_body: 'National Medical Commission (NMC)',
      accepted_entrance_exams: ['NEET PG', 'INI CET (for AIIMS, JIPMER, PGIMER, NIMHANS)'],
      counselling_routes: ['MCC NEET PG Counselling (50% AIQ, Central/Deemed Univs, AFMS)', 'State PG Medical Counselling (50% State Quota)'],
      career_scope: 'Consultant Physician / Surgeon in Tertiary Hospitals, Assistant Professor in Medical Colleges, Clinical Super-Specialist via NEET SS (DM / MCh), Medical Director.',
      top_specializations: ['MD General Medicine', 'MS General Surgery', 'MD Radio-Diagnosis', 'MD Pediatrics', 'MS Obstetrics & Gynecology', 'MS Orthopedics', 'MD Dermatology, Venereology & Leprosy', 'MD Anesthesiology'],
    },
    {
      name: 'Master of Business Administration',
      short_name: 'MBA / PGDM',
      slug: 'mba-management-postgraduate',
      degree_level: 'PG',
      stream: 'Management',
      duration_years: 2.0,
      eligibility_summary: 'Bachelor’s degree in any discipline with at least 50% marks (45% for SC/ST/PwD). Final year graduating students eligible to appear.',
      stream_prerequisites: ['Any Bachelor Degree (B.Tech, B.Sc, B.Com, BA, BBA, MBBS, LLB)'],
      lateral_entry_available: false,
      regulatory_body: 'AICTE / UGC',
      accepted_entrance_exams: ['CAT', 'XAT', 'NMAT', 'SNAP', 'CMAT', 'GMAT', 'MAT', 'State MBA CETs (MAH MBA CET)'],
      counselling_routes: ['IIM CAP & Individual IIM PI/WAT Rounds', 'XLRI / SPJIMR / FMS Individual Selection Portals', 'State Centralized MBA CAP'],
      career_scope: 'Management Consultant (MBB / Big 4), Investment Banker, Venture Capital Associate, Product Manager, Brand & Marketing Director, Chief Financial Officer (CFO), Entrepreneur.',
      top_specializations: ['Finance & Investment Banking', 'Strategy & Management Consulting', 'Product Management & Technology', 'Marketing & Brand Strategy', 'Operations & Supply Chain Management', 'Human Resources & Organizational Behavior'],
    },
    {
      name: 'Polytechnic Engineering Diploma',
      short_name: 'Polytechnic Diploma',
      slug: 'polytechnic-engineering-diploma',
      degree_level: 'Diploma',
      stream: 'Engineering',
      duration_years: 3.0,
      eligibility_summary: 'Passed Class 10 (Secondary School Examination) with Science and Mathematics with minimum 35-50% marks.',
      stream_prerequisites: ['Class 10 Pass'],
      lateral_entry_available: true,
      regulatory_body: 'State Board of Technical Education (SBTE) / AICTE',
      accepted_entrance_exams: ['State Polytechnic Entrance Exams (JEECUP UP, MP PPT, Delhi CET, AP POLYCET, TS POLYCET, JEXPO West Bengal)'],
      counselling_routes: ['State Board of Technical Education Online Counselling'],
      career_scope: 'Junior Engineer (JE) in SSC JE / RRB JE / State Electricity Boards / PWD / CPWD, Industrial Technician, Direct Lateral Entry Admission to 2nd year B.Tech/B.E. (LEET).',
      top_specializations: ['Mechanical Engineering', 'Electrical Engineering', 'Civil Engineering', 'Computer Science & Engineering', 'Automobile Engineering', 'Electronics Engineering'],
    },
    {
      name: 'Industrial Training Institute Certificate (ITI)',
      short_name: 'ITI Craftsman Certificate',
      slug: 'iti-trades-craftsman',
      degree_level: 'Certificate',
      stream: 'Vocational',
      duration_years: 2.0,
      eligibility_summary: 'Passed Class 10 (or Class 8 for select non-engineering trades) with Science and Mathematics.',
      stream_prerequisites: ['Class 10 Pass'],
      lateral_entry_available: true,
      regulatory_body: 'National Council for Vocational Training (NCVT) / Directorate General of Training (DGT)',
      accepted_entrance_exams: ['State ITI Merit Admission / State ITI Entrance'],
      counselling_routes: ['State DGT / ITI Online Counselling Portals'],
      career_scope: 'Technician / Assistant Loco Pilot in Indian Railways (RRB ALP & Technician), Tradesman in DRDO / ISRO / Ordnance Factories / PSUs (BHEL, NTPC, ONGC), Lateral entry to Polytechnic 2nd year.',
      top_specializations: ['Electrician (2 Years)', 'Fitter (2 Years)', 'Electronic Mechanic (2 Years)', 'Mechanic Motor Vehicle (MMV)', 'Welder (1 Year)', 'Turner (2 Years)', 'COPA (Computer Operator & Programming Assistant - 1 Year)'],
    },
  ];

  for (const cr of coursesData) {
    await query(
      `INSERT INTO courses (
        name, short_name, slug, degree_level, stream, duration_years,
        eligibility_summary, stream_prerequisites, lateral_entry_available,
        regulatory_body, accepted_entrance_exams, counselling_routes, career_scope,
        top_specializations, is_verified, last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, true, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        eligibility_summary = EXCLUDED.eligibility_summary,
        accepted_entrance_exams = EXCLUDED.accepted_entrance_exams,
        counselling_routes = EXCLUDED.counselling_routes,
        career_scope = EXCLUDED.career_scope,
        top_specializations = EXCLUDED.top_specializations,
        last_verified_at = NOW()`,
      [
        cr.name,
        cr.short_name,
        cr.slug,
        cr.degree_level,
        cr.stream,
        cr.duration_years,
        cr.eligibility_summary,
        JSON.stringify(cr.stream_prerequisites),
        cr.lateral_entry_available,
        cr.regulatory_body,
        JSON.stringify(cr.accepted_entrance_exams),
        JSON.stringify(cr.counselling_routes),
        cr.career_scope,
        JSON.stringify(cr.top_specializations),
      ]
    );
  }
  console.log(`Seeded ${coursesData.length} Undergraduate & Postgraduate Courses.`);

  // 6. Seed Detailed Pathways (Class 10, 12, UG, PG)
  const pathwaysData = [
    {
      stage_from: 'Class 10',
      title: 'Complete Career & Academic Pathways After Class 10 (Secondary School)',
      slug: 'pathways-after-class-10',
      category: 'School-to-Higher-Ed',
      summary: 'Comprehensive official roadmap for students after completing Class 10. Highlights senior secondary streams (PCM, PCB, Commerce, Arts), 3-Year Polytechnic Engineering Diplomas with lateral entry to B.Tech, and 2-Year ITI Trades leading to Government PSU/Railway recruitment.',
      flow_stages: [
        {
          level: 'Stage 1: Immediate Decision Gate',
          step_title: 'Choose Educational Track After Class 10',
          description: 'Students can branch into Senior Secondary Schooling (Class 11 & 12), Polytechnic Diploma, or ITI Skill Certification.',
          options: [
            'Class 11-12 Senior Secondary (Central/State Boards): Science (PCM/PCB), Commerce, Arts/Humanities',
            '3-Year Polytechnic Diploma (Technical Board): Direct entrance into engineering trades',
            '1-2 Year ITI Vocational Training (NCVT/SCVT): Skill certification for immediate technical recruitment',
          ],
        },
        {
          level: 'Stage 2: Entrance & Admission Route',
          step_title: 'Admission / Entrance Examinations',
          description: 'Merit-based admissions for school boards and state-level entrance examinations for polytechnics.',
          options: [
            'State Polytechnic Entrance: JEECUP (UP), MP PPT, Delhi CET, AP POLYCET, TS POLYCET, JEXPO',
            'State ITI Online Merit Counselling via DGT portals',
            'Class 11 School Board Admissions (CBSE, CISCE, State Boards) based on Class 10 Board Marks',
          ],
        },
        {
          level: 'Stage 3: Progression & Lateral Mobility',
          step_title: 'Bridging into Undergraduate Programs',
          description: 'Polytechnic Diploma holders are eligible for Lateral Entry (LEET) directly into 2nd year B.Tech/B.E., bypassing Class 11-12.',
          options: [
            'Class 12 Pass → National Entrance Exams (JEE Main, NEET UG, CUET UG, CLAT, NDA)',
            'Polytechnic Diploma Pass → Direct Admission to B.Tech 2nd Year (LEET / State Lateral Entry)',
            'ITI Pass → RRB Assistant Loco Pilot / Technician & Lateral Entry to 2nd Year Polytechnic',
          ],
        },
      ],
      entrance_exams: ['JEECUP', 'MP PPT', 'AP POLYCET', 'TS POLYCET', 'Delhi CET', 'JEXPO'],
      counselling_systems: ['State Board of Technical Education Online Counselling', 'State ITI Online Counselling'],
      courses_accessible: ['Class 11-12 Science (PCM/PCB)', 'Class 11-12 Commerce', 'Class 11-12 Arts/Humanities', 'Polytechnic Diploma in Mechanical/Civil/EE/CSE', 'ITI Electrician/Fitter/COPA'],
      institutions_types: ['Senior Secondary Schools / Junior Colleges', 'Government Polytechnic Colleges', 'Industrial Training Institutes (ITIs)'],
      career_outcomes: ['Junior Engineer (JE) after Diploma', 'Railway Technician / ALP after ITI', 'Full eligibility for all higher undergraduate degrees after Class 12'],
      govt_exam_eligibility: ['SSC MTS (Multi-Tasking Staff - 10th Pass)', 'SSC GD Constable (10th Pass)', 'Indian Army Agniveer General Duty (10th Pass)', 'Indian Navy MR (Matric Recruit)', 'Railway Group D (10th + ITI)'],
    },
    {
      stage_from: 'Class 12 (PCM)',
      title: 'Class 12 Science (PCM) — Engineering, Technology, Architecture & Defence Ecosystem',
      slug: 'pathways-after-class-12-pcm',
      category: 'Higher-Education',
      summary: 'Complete pathway for Physics, Chemistry, and Mathematics students covering JEE Main, JEE Advanced, BITSAT, NDA, NATA, JoSAA/CSAB counselling, IITs, NITs, B.Tech, Merchant Navy, and career outcomes.',
      flow_stages: [
        {
          level: 'Stage 1: Entrance Examinations',
          step_title: 'Appear for National / State Engineering & Defence Entrance Exams',
          description: 'Students appear in national and state level competitive tests according to target colleges and careers.',
          options: [
            'JEE Main (Session 1 & 2) → For NITs, IIITs, GFTIs and screening for JEE Advanced',
            'JEE Advanced → Top 2,50,000 JEE Main qualifiers compete for 23 IITs',
            'State Engineering CETs: MHT CET, WBJEE, KCET, COMEDK, GUJCET, KEAM',
            'Private University Tests: BITSAT (BITS Pilani/Goa/Hyderabad), VITEEE, SRMJEEE, MET',
            'Architecture: NATA & JEE Main Paper 2A (B.Arch) / Paper 2B (B.Plan)',
            'Defence: UPSC NDA & NA Examination (Army, Navy, Air Force officer commission)',
            'Maritime: IMU CET (Indian Maritime University for B.Tech Marine & B.Sc Nautical Science)',
          ],
        },
        {
          level: 'Stage 2: Centralized & State Counselling',
          step_title: 'Participate in Official Seat Allocation Systems',
          description: 'Official seat allocation based on verified merit ranks, normalized marks, and priority choice lists.',
          options: [
            'JoSAA (6 Rounds) for IITs, NITs, IIITs, and GFTIs',
            'CSAB Special Rounds (2 Rounds) for vacant seats in NIT+ system',
            'State Centralized Counselling (MHT CET CAP, WBJEEB, UPTAC, DTE MP, TNEA, KEAM)',
            'COA & State Architecture Admission Counselling for B.Arch',
          ],
        },
        {
          level: 'Stage 3: Undergraduate Degrees & Campus Life',
          step_title: 'Enroll in 4-Year B.Tech / 5-Year B.Arch / Defence Academy',
          description: 'Comprehensive 4-year engineering curriculum with industry internships and minor specializations.',
          options: [
            'B.Tech / B.E. in CSE, AI/ML, ECE, Electrical, Mechanical, Civil, Chemical, Aerospace',
            'B.Arch / B.Plan (5 Years / 4 Years)',
            'National Defence Academy (NDA Khadakwasla - 3 Years Training + 1 Year IMA/AFA/INA)',
          ],
        },
        {
          level: 'Stage 4: Post-B.Tech Gateways & Career Horizon',
          step_title: 'PG Entrance, PSU Jobs & Global Career Opportunities',
          description: 'Higher studies, government technical commissions, or top-tier software and engineering roles.',
          options: [
            'GATE Examination → M.Tech at IITs via CCMT/COAP + Direct PSU Executive Trainee Recruitment (ONGC, IOCL, NTPC, BHEL, DRDO)',
            'CAT / GMAT → MBA at IIMs, XLRI, FMS',
            'UPSC Engineering Services Examination (ESE) → Indian Railway, CPWD, MES Class-1 Officer',
            'UPSC Civil Services Examination (IAS / IPS / IFS)',
            'Direct Campus Recruitment as Software Development Engineer, Hardware Engineer, Data Analyst',
          ],
        },
      ],
      entrance_exams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'MHT CET', 'WBJEE', 'KCET', 'NATA', 'UPSC NDA', 'IMU CET'],
      counselling_systems: ['JoSAA', 'CSAB', 'State DTE Counselling', 'TNEA', 'WBJEEB', 'SSB Interview (NDA)'],
      courses_accessible: ['B.Tech / B.E.', 'B.Arch', 'B.Plan', 'BS-MS Dual Degree', 'B.Sc Nautical Science', 'Indian Armed Forces Permanent Commission'],
      institutions_types: ['IITs (23)', 'NITs (32)', 'IIITs (26)', 'BITS Pilani', 'National Defence Academy', 'State Govt Engineering Colleges'],
      career_outcomes: ['Software Development Engineer (SDE)', 'PSU Executive Engineer', 'Commissioned Defence Officer', 'Licensed Architect', 'Research Scientist via GATE/PhD'],
      govt_exam_eligibility: ['UPSC NDA & NA (Class 12 PCM)', 'Indian Navy 10+2 B.Tech Cadet Entry Scheme', 'Indian Army 10+2 Technical Entry Scheme (TES)', 'Indian Air Force Agniveer Vayu (Science)'],
    },
    {
      stage_from: 'Class 12 (PCB)',
      title: 'Class 12 Science (PCB) — Medicine, Dentistry, AYUSH, Nursing, Pharmacy & Allied Health',
      slug: 'pathways-after-class-12-pcb',
      category: 'Higher-Education',
      summary: 'Complete ecosystem for Biology students covering NEET UG, MCC All India Counselling, State 85% DME Counselling, AACCC AYUSH Counselling, MBBS, BDS, BAMS, B.Sc Nursing, B.Pharm, BPT, BVSc, and progression to NEET PG/MDS.',
      flow_stages: [
        {
          level: 'Stage 1: Entrance Examination Gate',
          step_title: 'Qualify National Eligibility cum Entrance Test (NEET UG)',
          description: 'Single mandatory national entrance test for all undergraduate medical, dental, and AYUSH seats across India.',
          options: [
            'NEET (UG) conducted by NTA: Single offline pen-and-paper examination covering Physics, Chemistry, Biology',
            'AIIMS B.Sc Nursing / Paramedical Entrance Examination (conducted directly by AIIMS New Delhi)',
            'State Pharmacy Entrance Tests (MHT CET, KCET, WBJEE, State CETs for B.Pharm)',
          ],
        },
        {
          level: 'Stage 2: Multi-Tier Counselling Systems',
          step_title: 'Participate in Medical & Allied Counselling',
          description: 'Students register on specific central and state counselling portals based on seat quota and institutional type.',
          options: [
            'MCC (Medical Counselling Committee): 15% AIQ MBBS/BDS, 100% AIIMS, JIPMER, AMU, BHU, Deemed Medical Colleges, Central B.Sc Nursing',
            'State DME Counselling: 85% State Quota MBBS/BDS in Government & Private State Medical Colleges',
            'AACCC Counselling: 15% All India Quota BAMS, BHMS, BUMS, BSMS in Government & Central Institutes',
            'Veterinary Council of India (VCI): 15% All India Quota B.V.Sc & A.H. seats via NEET score',
            'State Pharmacy & Nursing Admission Portals for B.Pharm & B.Sc Nursing',
          ],
        },
        {
          level: 'Stage 3: Undergraduate Degree & Compulsory Internship',
          step_title: 'Complete Professional Degree & Statutory Licensing',
          description: 'Rigorous clinical and academic training followed by mandatory rotating clinical internship.',
          options: [
            'MBBS (4.5 Years Academic + 1 Year Compulsory Rotatory Medical Internship) → NMC Permanent Registration',
            'BDS (4 Years Academic + 1 Year Dental Internship) → DCI Dental Registration',
            'BAMS / BHMS (4.5 Years + 1 Year Internship) → NCISM / NCH Registration',
            'B.Sc Nursing (4 Years Clinical Degree) → State Nursing Council RN / RM License',
            'B.Pharm (4 Years Pharmaceutical Sciences) → PCI Registered Pharmacist',
            'B.V.Sc & A.H. (4.5 Years + 1 Year Internship) → VCI Registered Veterinary Doctor',
          ],
        },
        {
          level: 'Stage 4: Post-Graduate Medical Specialization & Practice',
          step_title: 'Super-Specialization & Apex Healthcare Careers',
          description: 'National post-graduate entrance examinations for MD/MS/MDS or specialist hospital practice.',
          options: [
            'NEET PG / INI CET → 3-Year MD / MS in Medicine, Surgery, Pediatrics, Radiodiagnosis, Orthopedics',
            'NEET MDS → 3-Year MDS in Orthodontics, Oral Surgery, Periodontics',
            'AIAPGET → MD / MS in Ayurveda / Homeopathy / Unani',
            'GPAT → M.Pharm in Pharmaceutics / Pharmacology / Drug Regulatory Affairs',
            'AIIMS NORCET → Nursing Officer Recruitment in AIIMS (Pay Level 7: ₹44,900 – ₹1,42,400)',
            'Super-Specialization: NEET SS → 3-Year DM / MCh (Cardiology, Neurology, Neurosurgery, Surgical Oncology)',
          ],
        },
      ],
      entrance_exams: ['NEET UG', 'AIIMS B.Sc Nursing', 'State Pharmacy CETs', 'NEET PG', 'INI CET', 'NEET MDS', 'AIAPGET'],
      counselling_systems: ['MCC (Medical Counselling Committee)', 'AACCC (Ayush Counselling)', 'State DME Medical Counselling', 'VCI Veterinary Counselling'],
      courses_accessible: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'B.Sc Nursing', 'B.Pharm', 'B.P.T. (Physiotherapy)', 'B.V.Sc & A.H.'],
      institutions_types: ['AIIMS (20+ Institutes across India)', 'Government Medical Colleges (GMCs)', 'Government Dental Colleges', 'National AYUSH Institutes (NIA, NIH)', 'Veterinary Universities'],
      career_outcomes: ['Registered Medical Practitioner (Doctor)', 'Dental Surgeon', 'Ayurvedic Medical Officer', 'AIIMS Nursing Officer', 'Drug Inspector', 'Specialist Clinical Consultant'],
      govt_exam_eligibility: ['UPSC Combined Medical Services (CMS) for MBBS Graduates', 'Armed Forces Medical Services (AFMS / Military Doctors)', 'State Medical Officer (MO) Recruitment via State PSCs', 'AIIMS NORCET (B.Sc Nursing)'],
    },
    {
      stage_from: 'Class 12 (Commerce)',
      title: 'Class 12 Commerce — Chartered Accountancy, Management, Economics & Corporate Finance',
      slug: 'pathways-after-class-12-commerce',
      category: 'Higher-Education',
      summary: 'Complete roadmap for Commerce students covering ICAI Chartered Accountancy (CA), IIM IPMAT (5-Year Integrated MBA), CUET UG for top commerce colleges (SRCC, Hindu), Company Secretary (CS), and Banking/Finance careers.',
      flow_stages: [
        {
          level: 'Stage 1: Entrance & Professional Registration Gate',
          step_title: 'Entrance Examinations & Statutory Registrations',
          description: 'Students choose between statutory professional qualifications and premier collegiate/university entrance tests.',
          options: [
            'ICAI CA Foundation: Registration with Institute of Chartered Accountants of India (ICAI)',
            'IPMAT (IIM Indore / Rohtak / Ranchi / Jammu / Bodh Gaya) for 5-Year Integrated Management',
            'CUET UG (Common University Entrance Test) for B.Com (Hons), Economics (Hons), BMS at Delhi University, BHU, Jamia',
            'ICSI CSEET: Company Secretary Executive Entrance Test with Institute of Company Secretaries of India',
            'ICMAI CMA Foundation: Cost & Management Accountancy qualification',
          ],
        },
        {
          level: 'Stage 2: Degree / Professional Course Progression',
          step_title: 'Pursue Undergraduate Degree & Professional Stages',
          description: 'Concurrent pursuit of collegiate degrees and statutory professional stages with articleship training.',
          options: [
            'B.Com (Hons) / B.Com / Bachelor of Management Studies (BMS) / BBA (3-4 Years FYUP)',
            'ICAI CA Intermediate (Group 1 & 2) + Mandatory 2-Year Practical Articleship under Practicing CA',
            'IIM 5-Year Integrated Programme in Management (BBA + MBA dual qualification)',
          ],
        },
        {
          level: 'Stage 3: Advanced Qualifications & Master’s Degrees',
          step_title: 'CA Final, CFA, MBA & Specialized Certifications',
          description: 'Apex certifications in global finance, valuation, investment banking, and taxation.',
          options: [
            'ICAI CA Final → Qualified Chartered Accountant (Fellow / Associate Member ICAI)',
            'CAT / XAT / GMAT → Top-tier MBA in Finance from IIM Ahmedabad, IIM Bangalore, IIM Calcutta, XLRI',
            'Global Professional Certifications: CFA (Chartered Financial Analyst), FRM (Financial Risk Manager), ACCA',
          ],
        },
      ],
      entrance_exams: ['ICAI CA Foundation', 'IPMAT', 'CUET UG', 'ICSI CSEET', 'ICMAI CMA Foundation', 'CAT', 'XAT'],
      counselling_systems: ['DU CSAS (Common Seat Allocation System)', 'IIM IPM Direct Admissions', 'ICAI Examination & Registration Portal'],
      courses_accessible: ['B.Com (Hons)', 'BBA / BMS', '5-Year Integrated MBA (IPM)', 'BA (Hons) Economics', 'Chartered Accountancy (CA)', 'Company Secretary (CS)'],
      institutions_types: ['Shri Ram College of Commerce (SRCC)', 'IIM Indore / IIM Rohtak', 'Lady Shri Ram College', 'Hindu College', 'St. Xavier’s College Mumbai/Kolkata'],
      career_outcomes: ['Chartered Accountant (Auditor / Tax Consultant)', 'Investment Banker (M&A, Equity Capital Markets)', 'Corporate Financial Controller (CFO)', 'Management Consultant', 'Equity Research Analyst'],
      govt_exam_eligibility: ['RBI Grade B Officer (Any Graduate 60%)', 'SEBI Grade A Officer (General / Legal / Accounts)', 'UPSC Civil Services (IAS / IRS Income Tax / Customs)', 'IBPS PO / SBI PO (Probationary Officer)', 'SSC CGL (Assistant Audit Officer / Assistant Accounts Officer)'],
    },
    {
      stage_from: 'Class 12 (Arts/Humanities)',
      title: 'Class 12 Arts & Humanities — Law, Civil Services, Public Policy, Journalism & Design',
      slug: 'pathways-after-class-12-arts',
      category: 'Higher-Education',
      summary: 'Comprehensive roadmap for Humanities students covering CLAT (5-Year Law at NLUs), CUET UG (Top Arts & Social Science colleges), Design Entrances (NID, NIFT, UCEED), and Civil Services / Judiciary career trajectories.',
      flow_stages: [
        {
          level: 'Stage 1: Entrance Examinations',
          step_title: 'Appear for National Law, University & Creative Entrances',
          description: 'Students choose between premier National Law Universities, Central Universities, and premier design schools.',
          options: [
            'CLAT UG & AILET: 5-Year Integrated BA LLB / BBA LLB at 24 National Law Universities (NLSIU, NALSAR, NUJS, NLU Delhi)',
            'CUET UG: BA (Hons) in Political Science, History, Economics, Psychology, English, Sociology at DU, JNU, BHU',
            'Design & Fashion Entrances: NID DAT (National Institute of Design), NIFT Entrance (National Institute of Fashion Technology), UCEED (IIT Bombay)',
            'Mass Communication: IIMC Entrance Exam, FTII Pune, St. Xavier’s BMM',
          ],
        },
        {
          level: 'Stage 2: Degree Programs & Specialized Training',
          step_title: 'Complete Undergraduate Degree & Academic Rigor',
          description: 'Building deep analytical, legal, policy, creative, and linguistic foundations.',
          options: [
            '5-Year Integrated BA LLB (Hons) / BBA LLB (Hons)',
            '3-4 Year BA (Hons) in Political Science, International Relations, Economics, Psychology',
            '4-Year Bachelor of Design (B.Des) / Bachelor of Fine Arts (BFA)',
            '3-Year Bachelor of Journalism & Mass Communication (BJMC)',
          ],
        },
        {
          level: 'Stage 3: Advanced Specialization & Civil Service Gateways',
          step_title: 'Judiciary, Civil Services, LLM, MA & International Fellowships',
          description: 'Entry into Apex Indian governance, judicial benches, policy think-tanks, and academia.',
          options: [
            'State Judicial Services Examination (PCS-J) → Civil Judge / Judicial Magistrate (Directly after LLB)',
            'UPSC Civil Services Examination (IAS / IPS / IFS / IRS) → Apex national governance leadership',
            'Bar Council of India All India Bar Examination (AIBE) → Advocate Certificate of Practice',
            'CUET PG / JEST → Master of Arts (MA) / Master of Public Policy (MPP) / Master of Laws (LLM)',
            'UGC NET JRF → Junior Research Fellowship & Assistant Professor in Central/State Universities',
          ],
        },
      ],
      entrance_exams: ['CLAT UG', 'AILET', 'CUET UG', 'NID DAT', 'NIFT Entrance', 'UCEED', 'UPSC CSE', 'State Judicial Services (PCS-J)'],
      counselling_systems: ['Consortium of NLUs Centralized Counselling', 'DU CSAS Portal', 'NIFT Central Counselling', 'NID Admission Portal'],
      courses_accessible: ['BA LLB (Hons) (5 Years)', 'BA (Hons) Political Science / History / Economics', 'Bachelor of Design (B.Des)', 'BJMC (Journalism)', 'Bachelor of Social Work (BSW)'],
      institutions_types: ['National Law Universities (NLSIU, NALSAR, NUJS)', 'St. Stephen’s College', 'Miranda House', 'National Institute of Design (NID Ahmedabad)', 'NIFT New Delhi'],
      career_outcomes: ['High Court / Supreme Court Advocate', 'Civil Judge / Magistrate via PCS-J', 'IAS / IPS / IFS Civil Servant', 'Public Policy Analyst (NITI Aayog / Think Tanks)', 'Senior Investigative Journalist / Media Producer'],
      govt_exam_eligibility: ['UPSC Civil Services Examination (Graduate in Any Stream)', 'State PSC State Services Exam (MPPSC, UPPSC, BPSC, MPSC)', 'State Judicial Services (LLB Pass)', 'SSC CGL (Assistant Section Officer in MEA / CSS)'],
    },
    {
      stage_from: 'UG Engineering (B.Tech)',
      title: 'After B.Tech / B.E. — GATE, PSUs, M.Tech, MBA, UPSC IES & Software Engineering',
      slug: 'pathways-after-btech-engineering',
      category: 'Graduation-to-Career',
      summary: 'Complete post-engineering ecosystem covering GATE (IIT M.Tech & Maharatna PSU Recruitment), CAT (IIM MBA), UPSC Engineering Services (IES), Tech Software Careers, and PhD Research routes.',
      flow_stages: [
        {
          level: 'Stage 1: Primary Post-Engineering Pathways',
          step_title: 'Select Career Direction in Final Year',
          description: 'Graduating engineers choose between technical specialization, management leadership, government public sector recruitment, or private corporate tech roles.',
          options: [
            'Track A: GATE Examination for M.Tech at IITs (via COAP/CCMT) and direct Maharatna PSU jobs (ONGC, IOCL, NTPC, BHEL, GAIL, HPCL, PGCIL, BARC, DRDO, ISRO)',
            'Track B: CAT / XAT / GMAT for MBA at premier IIMs and global business schools',
            'Track C: UPSC Engineering Services Examination (ESE) for Class-1 Group A gazetted engineering posts',
            'Track D: Direct Campus Placements & Off-campus Tech Recruitment (Product & Services Companies)',
            'Track E: Direct PhD / Research Fellowships at IISc, IITs, or international universities (GRE/TOEFL)',
          ],
        },
      ],
      entrance_exams: ['GATE', 'CAT', 'XAT', 'UPSC ESE (Engineering Services)', 'UPSC CSE', 'ISRO ICRB', 'BARC OCES/DGFS'],
      counselling_systems: ['COAP (IIT M.Tech Offers)', 'CCMT (NIT/IIIT Central Counselling)', 'IIM Interview Shortlists'],
      courses_accessible: ['M.Tech / M.E.', 'MBA / PGDM', 'Integrated M.Tech-PhD', 'Direct PhD at IITs/IISc', 'Post-Graduate Diploma in Industrial Management (PGDIM)'],
      institutions_types: ['IITs (23)', 'IISc Bangalore', 'IIMs (20+)', 'NITs (32)', 'Premier PSUs (ONGC, IOCL, BHEL)'],
      career_outcomes: ['Maharatna PSU Executive Trainee (Starting CTC ₹15-22 LPA)', 'Indian Engineering Services (IES) Officer', 'Software Development Engineer (SDE II/III)', 'Quantitative Finance Analyst', 'Research Scientist at ISRO/DRDO'],
      govt_exam_eligibility: ['UPSC Engineering Services Examination (B.Tech Required)', 'ISRO Scientist/Engineer ‘SC’ (B.Tech 65%)', 'DRDO Scientist ‘B’ (GATE Score)', 'SSC Junior Engineer / RRB Senior Section Engineer', 'UPSC Civil Services Examination'],
    },
    {
      stage_from: 'Graduation (Any Stream)',
      title: 'After Graduation (Any Bachelor’s Degree) — Central & State Government Recruitment Ecosystem',
      slug: 'pathways-after-graduation-govt-exams',
      category: 'Graduation-to-Career',
      summary: 'Complete guide for any graduate (BA, B.Sc, B.Com, B.Tech, BBA, BCA, MBBS) to navigate premier government career examinations: UPSC CSE (IAS/IPS), SSC CGL, Banking (IBPS/SBI PO), RBI Grade B, Defence (CDS/AFCAT), and State PSCs.',
      flow_stages: [
        {
          level: 'Stage 1: Government Career Classification',
          step_title: 'Identify Target Government Exam Stream',
          description: 'All central and state government recruitment boards accept recognized 3-year or 4-year undergraduate degrees in any discipline.',
          options: [
            'Civil Services & State Administration: UPSC CSE (IAS, IPS, IFS, IRS) & State PSCs (MPPSC, UPPSC, BPSC, MPSC, RAS)',
            'Central Ministries & Inspections: SSC CGL (Income Tax Inspector, GST Inspector, Assistant Section Officer, CBI Sub-Inspector)',
            'Banking & Financial Regulators: RBI Grade B Officer, SBI PO, IBPS PO, NABARD Grade A, SEBI Grade A',
            'Defence Services (Officers): UPSC CDS (IMA, OTA, INA, AFA) & AFCAT (Air Force Flying & Ground Duty)',
            'Indian Railways: RRB NTPC (Graduate Level: Station Master, Goods Train Manager, Commercial Apprentice)',
          ],
        },
      ],
      entrance_exams: ['UPSC CSE', 'SSC CGL', 'IBPS PO', 'SBI PO', 'RBI Grade B', 'UPSC CDS', 'AFCAT', 'State PSCs', 'RRB NTPC'],
      counselling_systems: ['UPSC Personality Test & Cadre Allocation', 'SSC Document Verification & Zone Allocation', 'IBPS Common Allotment to 11 Nationalized Banks'],
      courses_accessible: ['Direct Appointment as Gazetted / Non-Gazetted Government Officer', 'Foundation Training at LBSNAA (Mussoorie), SVPNPA (Hyderabad), NAAA (Shimla)', 'Bank Management Training at NIBM Pune / State Bank Academy'],
      institutions_types: ['Central Ministries & Departments of India', 'Reserve Bank of India', 'State Bank of India & Nationalized Banks', 'Indian Armed Forces Academies (IMA, AFA, INA, OTA)', 'Indian Railways Zones'],
      career_outcomes: ['Sub-Divisional Magistrate (SDM) / District Magistrate (DM) / Superintendent of Police (SP)', 'Income Tax Inspector / Customs Preventive Officer / CBI Sub-Inspector', 'Reserve Bank of India Grade B Manager', 'Bank Branch Manager / Scale-IV AGM', 'Commissioned Captain / Flight Lieutenant in Armed Forces'],
      govt_exam_eligibility: ['UPSC Civil Services (Age 21-32, Graduation)', 'SSC CGL (Age 18-32, Graduation)', 'IBPS PO / SBI PO (Age 20-30, Graduation)', 'RBI Grade B (Age 21-30, Graduation 60%)', 'UPSC CDS (Age 19-24, Graduation)'],
    },
  ];

  for (const pw of pathwaysData) {
    await query(
      `INSERT INTO student_pathways (
        stage_from, title, slug, category, summary, flow_stages,
        entrance_exams, counselling_systems, courses_accessible,
        institutions_types, career_outcomes, govt_exam_eligibility,
        is_verified, last_verified_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, true, NOW())
      ON CONFLICT (slug) DO UPDATE SET
        title = EXCLUDED.title,
        summary = EXCLUDED.summary,
        flow_stages = EXCLUDED.flow_stages,
        entrance_exams = EXCLUDED.entrance_exams,
        counselling_systems = EXCLUDED.counselling_systems,
        courses_accessible = EXCLUDED.courses_accessible,
        career_outcomes = EXCLUDED.career_outcomes,
        govt_exam_eligibility = EXCLUDED.govt_exam_eligibility,
        last_verified_at = NOW()`,
      [
        pw.stage_from,
        pw.title,
        pw.slug,
        pw.category,
        pw.summary,
        JSON.stringify(pw.flow_stages),
        JSON.stringify(pw.entrance_exams),
        JSON.stringify(pw.counselling_systems),
        JSON.stringify(pw.courses_accessible),
        JSON.stringify(pw.institutions_types),
        JSON.stringify(pw.career_outcomes),
        JSON.stringify(pw.govt_exam_eligibility),
      ]
    );
  }
  console.log(`Seeded ${pathwaysData.length} Student Pathways.`);

  console.log('--- Completed Comprehensive Education Ecosystem Seeding ---');
}

seedEducationEcosystem().catch(console.error).finally(() => process.exit(0));
